- name: Check for kwriteconfig5.
  ansible.builtin.stat:
    path: /usr/bin/kwriteconfig5
  register: kwriteconfig5

- name: Check for kreadconfig5.
  ansible.builtin.stat:
    path: /usr/bin/kreadconfig5
  register: kreadconfig5

- name: Configure the KDE Plasma desktop.
  when: kwriteconfig5.stat.exists and kwriteconfig5.stat.executable and kreadconfig5.stat.exists and kreadconfig5.stat.executable
  block:
    - name: Use double click to open folders.
      kconfig:
        file: ~/.config/kdeglobals
        group: KDE
        key: SingleClick
        value: "false"
        type: bool

    - name: Alacritty shortcuts.
      kconfig:
        file: ~/.config/kglobalshortcutsrc
        group: Alacritty.desktop
        key: "{{ setting[0] }}"
        value: "{{ setting[1] }}"
      loop:
        - ["_launch", "Ctrl+Alt+T\\\tMeta+Return"]
        - ["_k_friendly_name", "Alacritty"]
        # - ["New", ",,New Terminal"]
      loop_control:
        loop_var: setting

    - name: Set theme.
      kconfig:
        file: ~/.config/plasmarc
        group: Theme
        key: name
        value: breeze-dark

    - name: Set icon theme.
      kconfig:
        file: ~/.config/kdeglobals
        group: Icons
        key: Theme
        value: breeze-dark

    - name: Disable window shadows.
      kconfig:
        file: ~/.config/breezerc
        group: Common
        key: ShadowSize
        value: ShadowNone

    - name: Align title left.
      kconfig:
        file: ~/.config/breezerc
        group: Windeco
        key: TitleAlignment
        value: AlignLeft

    - name: Set window borders.
      kconfig:
        file: ~/.config/kwinrc
        group: org.kde.kdecoration2
        key: BorderSize
        value: Tiny

    - name: Disable automatic border size.
      kconfig:
        file: ~/.config/kwinrc
        group: org.kde.kdecoration2
        key: BorderSizeAuto
        value: "false"
        type: bool

    - name: Enable bismuth scripts.
      kconfig:
        file: ~/.config/kwinrc
        group: Plugins
        key: bismuthEnabled
        value: "true"
        type: bool

    - name: Change border colors.
      kconfig:
        file: ~/.config/kdeglobals
        group: WM
        key: frame
        value: "61,174,233"

    - name: Change border colors for inactive window.
      kconfig:
        file: ~/.config/kdeglobals
        group: WM
        key: inactiveFrame
        value: "239,240,241"

    - name: Add window minimum geometry size rule.
      block:
        - name: Set description.
          kconfig:
            file: ~/.config/kwinrulesrc
            group: eaa2366f-b4c5-4ecc-a72e-c22be46f4ffb
            key: Description
            value: "Set Minimum Geometry Size"

        - name: Set types.
          kconfig:
            file: ~/.config/kwinrulesrc
            group: eaa2366f-b4c5-4ecc-a72e-c22be46f4ffb
            key: types
            value: "1"

        - name: Set minsizerule.
          kconfig:
            file: ~/.config/kwinrulesrc
            group: eaa2366f-b4c5-4ecc-a72e-c22be46f4ffb
            key: minsizerule
            value: "2"

    - name: Activate window rules.
      block:
        - name: Set count.
          kconfig:
            file: ~/.config/kwinrulesrc
            group: General
            key: count
            value: "1"

        - name: Set rules.
          kconfig:
            file: ~/.config/kwinrulesrc
            group: General
            key: rules
            value: "eaa2366f-b4c5-4ecc-a72e-c22be46f4ffb"

    - name: Disable kwin shortcuts.
      kconfig:
        file: ~/.config/kglobalshortcutsrc
        group: kwin
        key: "{{ item['key'] }}"
        value: "{{ item['value'] }}"
      loop:
        - key: "Window Quick Tile Bottom"
          value: "none,none,Quick Tile Window to the Bottom"
        - key: "Window Quick Tile Bottom Left"
          value: "none,none,Quick Tile Window to the Bottom Left"
        - key: "Window Quick Tile Bottom Right"
          value: "none,none,Quick Tile Window to the Bottom Right"
        - key: "Window Quick Tile Left"
          value: "none,none,Quick Tile Window to the Left"
        - key: "Window Quick Tile Right"
          value: "none,none,Quick Tile Window to the Right"
        - key: "Window Quick Tile Top"
          value: "none,none,Quick Tile Window to the Top"
        - key: "Window Quick Tile Top Left"
          value: "none,none,Quick Tile Window to the Top Left"
        - key: "Window Quick Tile Top Right"
          value: "none,none,Quick Tile Window to the Top Right"

    - name: Enable kwin shortcuts.
      kconfig:
        file: ~/.config/kglobalshortcutsrc
        group: kwin
        key: "{{ item['key'] }}"
        value: "{{ item['value'] }}"
      loop:
        - key: "bismuth_focus_left_window"
          value: "Meta+Left,none,Bismuth: Focus Left Window"
        - key: "bismuth_focus_right_window"
          value: "Meta+Right,none,Bismuth: Focus Right Window"
        - key: "bismuth_focus_bottom_window"
          value: "Meta+Down,none,Bismuth: Focus Bottom Window"
        - key: "bismuth_focus_upper_window"
          value: "Meta+Up,none,Bismuth: Focus Upper Window"
        - key: "bismuth_move_window_to_left_pos"
          value: "Meta+Shift+Left,none,Bismuth: Move Window Left"
        - key: "bismuth_move_window_to_right_pos"
          value: "Meta+Shift+Right,none,Bismuth: Move Window Right"
        - key: "bismuth_move_window_to_upper_pos"
          value: "Meta+Shift+Up,none,Bismuth: Move Window Up"
        - key: "bismuth_move_window_to_bottom_pos"
          value: "Meta+Shift+Up,none,Bismuth: Move Window Down"
        - key: "bismuth_toggle_window_floating"
          value: "Meta+Space,none,Bismuth: Toggle Active Window Floating"
