- name: Find kwriteconfig executable.
  search_file:
    name: kwriteconfig5
    paths:
      - /usr/bin
      - /run/current-system/sw/bin/
    executable: true
  register: kwriteconfig_check

- name: Configure KDE.
  ansible.builtin.include_tasks: config.yml
  when: kwriteconfig_check.found
