export ZSHD="{{ home }}/.zsh.d"

[ -f "{{ home }}/.profile" ] && source "{{ home }}/.profile"


unsetopt BEEP
setopt AUTO_CD
setopt GLOB_DOTS
setopt NOMATCH
setopt MENU_COMPLETE
setopt EXTENDED_GLOB
setopt INTERACTIVE_COMMENTS

# completion system
autoload -Uz compinit
zstyle ':completion:*' menu yes select
zmodload zsh/complist
_comp_options+=(globdots)
zle_highlight=('paste:none')

autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search

# colors
autoload -Uz colors && colors

# history
setopt APPEND_HISTORY         # append history to the history file
setopt EXTENDED_HISTORY       # write extended history information
setopt HIST_EXPIRE_DUPS_FIRST # expire duplicates first when trimming history
setopt HIST_IGNORE_DUPS       # don't record an entry that was just recorded again
setopt HIST_IGNORE_ALL_DUPS   # delete old recorded entry if new entry is a duplicate
setopt HIST_FIND_NO_DUPS      # do not display a line previously found
setopt HIST_IGNORE_SPACE      # ignore commands that start with a space
setopt HIST_SAVE_NO_DUPS      # don't write duplicate entries in the history file
setopt HIST_REDUCE_BLANKS     # remove superfluous blanks before recording entry
setopt HIST_VERIFY            # don't execute immediately upon history expansion
setopt INC_APPEND_HISTORY     # write to the history file immediately, not when shell exits
setopt SHARE_HISTORY          # share history between all sessions
HISTFILE="{{ home }}/.zsh_history"
HISTSIZE=1000000
SAVEHIST=1000000

# keybindings
ctrl-z-toggle () {
  if [[ $#BUFFER -eq 0 ]]; then
    BUFFER="fg"
    zle accept-line
  else
    zle push-input
    zle clear-screen
  fi
}

zle -N ctrl-z-toggle
bindkey '^Z' ctrl-z-toggle


bindkey "^[[H" beginning-of-line
bindkey "^[[F" end-of-line
bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word
bindkey "^[[3~" delete-char
bindkey "^[[1;3D" backward-word
bindkey "^[[1;3C" forward-word

bindkey -M menuselect '?' history-incremental-search-forward
bindkey -M menuselect '/' history-incremental-search-backward

# hooks
{% for hook in zsh_hooks %}
{{ hook }}
{% endfor %}

# aliases
{% for alias in aliases %}
alias {{ alias[0] }}="{{ alias[1] }}"
{% endfor %}

# exports
PATH="{{ home }}/.local/bin:${PATH}"

{% for export in exports %}
export {{ export|upper }}="{{ exports[export] }}"
{% endfor %}

if (( $+commands[pip] )); then
	eval "$(pip completion --zsh)"
fi


# completions
fpath+={{ home }}/.zsh.d/plugins/conda-zsh-completion
fpath+={{ home }}/.zfunc
for dump in "{{ home }}/.zcompdump"(N.mh+24); do
  compinit
done
compinit -C
