- name: Symlink fish config.
  ansible.builtin.file:
    src: "{{ role_path }}/files/fish"
    dest: "~/.config/fish"
    state: link
    force: yes
    follow: no

- name: Check if fish is installed.
  ansible.builtin.stat:
    path: /usr/bin/fish
  register: fish_stat

- name: Store whether fish is installed.
  ansible.builtin.set_fact:
    fish_found: "{{ fish_stat.stat.exists and fish_stat.stat.executable }}"
