- name: Symlink fish config.
  ansible.builtin.file:
    src: "{{ role_path }}/files/fish"
    dest: "~/.config/fish"
    state: link
    force: yes
    follow: no

- name: Check if fish is installed.
  ansible.builtin.stat:
    path: /usr/bin/fish
  register: fish_stat

- name: Store whether fish is missing.
  ansible.builtin.set_fact:
    fish_missing: "{{ not (fish_stat.stat.exists and fish_stat.stat.executable) }}"

- name: Install fish.
  when: fish_missing and homebrew_enabled
  community.general.homebrew:
    name: fish
    state: present
    path: "{{ homebrew_path }}"

- name: Remove homebrew fish.
  when: (not fish_missing) and homebrew_present
  community.general.homebrew:
    name: fish
    state: absent
    path: "{{ homebrew_path }}"
