home_dir: "{{ lookup('env', 'HOME') }}"
anaconda_prefix: "{{ home_dir }}/.local/opt/anaconda3"
aliases:
  - ["cp", "cp -i"]
  - ["mv", "mv -i"]
  - ["rm", "rm -i"]
  - ["..", "cd .."]
  - ["...", "cd ../.."]
  - ["....", "cd ../../.."]
  - [".....", "cd ../../../.."]
homebrew_enabled: true
homebrew_prefix: "{{ home_dir }}/.linuxbrew"
homebrew_path: "{{ homebrew_prefix }}/bin"
flatpak_remotes:
  - name: flathub
    url: https://flathub.org/repo/flathub.flatpakrepo
environment_variables:
  XDG_CONFIG_HOME: "{{ home_dir }}/.config"
  XDG_CACHE_HOME: "{{ home_dir }}/.cache"
  XDG_DATA_HOME: "{{ home_dir }}/.local/share"
  XDG_STATE_HOME: "{{ home_dir }}/.local/statstate"
  EDITOR: "vim"
  GPG_TTY: "$(tty)"
  PATH: "{{ home_dir }}/.local/bin:${PATH}"
