anaconda_prefix: ~/.local/opt/anaconda3
aliases:
  - ["cp", "cp -i"]
  - ["mv", "mv -i"]
  - ["rm", "rm -i"]
  - ["..", "cd .."]
  - ["...", "cd ../.."]
  - ["....", "cd ../../.."]
  - [".....", "cd ../../../.."]
homebrew_prefix: ~/.linuxbrew
homebrew_path: "{{ homebrew_prefix }}/bin"
