HOME: "{{ lookup('env', 'HOME') }}"
xdg:
  config_home: "{{ HOME }}/.config"
  cache_home: "{{ HOME }}/.cache"
  data_home: "{{ HOME }}/.local/share"
  state_home: "{{ HOME }}/.local/statstate"
anaconda_prefix: "{{ HOME }}/.local/opt/anaconda3"
aliases:
  - ["cp", "cp -i"]
  - ["mv", "mv -i"]
  - ["rm", "rm -i"]
exports:
  EDITOR: "/usr/bin/vim"
  GPG_TTY: "$(tty)"
bash_hooks: []
zsh_hooks: []
fish_hooks: []
bash_aliases:
  - ["~", "cd {{ HOME }}"]
  - ["..", "cd .."]
  - ["...", "cd ../.."]
  - ["....", "cd ../../.."]
  - [".....", "cd ../../../.."]
