home_dir: "{{ lookup('env', 'HOME') }}"
anaconda_prefix: "{{ home_dir }}/.local/opt/anaconda3"
aliases:
  - ["cp", "cp -i"]
  - ["mv", "mv -i"]
  - ["rm", "rm -i"]
  - ["..", "cd .."]
  - ["...", "cd ../.."]
  - ["....", "cd ../../.."]
  - [".....", "cd ../../../.."]
homebrew_prefix: "{{ home_dir }}/.linuxbrew"
homebrew_path: "{{ homebrew_prefix }}/bin"
flatpak_remotes:
  - name: flathub
    url: https://flathub.org/repo/flathub.flatpakrepo
