anaconda_prefix: "{{ home }}/.local/opt/anaconda3"
aliases:
  - ["cp", "cp -i"]
  - ["mv", "mv -i"]
  - ["rm", "rm -i"]
exports:
  EDITOR: "/usr/bin/vim"
  GPG_TTY: "$(tty)"
bash_hooks: []
zsh_hooks: []
fish_hooks: []
bash_aliases:
  - ["~", "cd {{ home }}"]
  - ["..", "cd .."]
  - ["...", "cd ../.."]
  - ["....", "cd ../../.."]
  - [".....", "cd ../../../.."]
