- hosts: targets
  tasks:
    - name: fetch dotfiles
      git:
        accept_hostkey: yes
        repo: git@github.com:f-koehler/dotfiles.git
        dest: ~/.dotfiles
    - name: symlinks in ~/.config/
      file:
        src: "~/.dotfiles/{{ item }}"
        dest: "~/.config/{{ item }}"
        state: link
        force: yes
        follow: no
      loop:
        - alacritty
        - htop
        - khal
        - kitty
        - nvim
        - offlineimap
        - plasma-workspace
        - polybar
        - ranger
        - rofi
        - vdirsyncer
    - name: configure dircolors
      file:
        src: ~/.dotfiles/dircolors/src/dir_colors
        dest: ~/.dircolors
        state: link
        force: yes
        follow: no
    - name: configure emacs
      file:
        src: ~/.dotfiles/emacs
        dest: ~/.emacs.d
        state: link
        force: yes
        follow: no
    - name: symlink zsh config directory
      file:
        src: ~/.dotfiles/zsh
        dest: ~/.zsh.d
        state: link
        force: yes
        follow: no
    - name: symlink zsh config
      file:
        src: ~/.zsh.d/init.zsh
        dest: ~/.zshrc
        state: link
        force: yes
        follow: no
    - name: symlink p10k config
      file:
        src: ~/.zsh.d/p10k.zsh
        dest: ~/.p10k.zsh
        state: link
        force: yes
        follow: no
    - name: configure xresources
      file:
        src: ~/.dotfiles/xresources/src/nord
        dest: ~/.Xresources
        state: link
        force: yes
        follow: no
    - name: configure xdefaults
      file:
        src: ~/.dotfiles/xresources/src/nord
        dest: ~/.Xdefaults
        state: link
        force: yes
        follow: no
    - name: configure scripts
      file:
        src: ~/.dotfiles/scripts
        dest: ~/.scripts
        state: link
        force: yes
        follow: no
    - name: make sure to use ~/.tmux.conf instead of ~/.config/tmux/tmux.conf
      file:
        path: ~/.config/tmux
        state: absent
    - name: link tmux.conf
      file:
        src: ~/.dotfiles/tmux/tmux.conf
        dest: ~/.tmux.conf
        state: link
        force: yes
        follow: no
    - name: link tmux dir
      file:
        src: ~/.dotfiles/tmux/
        dest: ~/.tmux
        state: link
        force: yes
        follow: no
