# vim: ft=yaml.ansible
- hosts: targets
  tasks:
    - block:
      - name: Obtain zsh config
        git:
          accept_hostkey: yes
          dest: ~/.zsh.d
          recursive: yes
          repo: "git@github.com:f-koehler/config-zsh.git"
      - name: Symlink .zshrc file
        file:
          dest: ~/.zshrc
          src: ~/.zsh.d/init.zsh
          state: link

    - block:
      - name: Obtain neovim config
        git:
          accept_hostkey: yes
          dest: ~/.config/nvim/
          recursive: yes
          repo: "git@github.com:f-koehler/config-vim.git"

    - block:
        - name: Obtain polybar config
          git:
            accept_hostkey: yes
            dest: ~/.config/polybar
            repo: "git@github.com:f-koehler/config-polybar.git"

