#!/bin/bash
set -euf -o pipefail

COMMAND=$(cat <<-END
    git fetch origin
    BRANCH=\$(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@')
    git checkout \$BRANCH
    git pull origin \$BRANCH
END
)
git submodule foreach sh -c "$COMMAND"
