- hosts: all
  pre_tasks:
    - name: Load config.
      ansible.builtin.include_vars: config.yml
  # roles:
  #   # - gtk
  #   # - kde
  #   # # - nvim
  #   # - polybar
  #   # # - ranger
  #   # - rofi
  #   # - symlinks
  tasks:
    # Install fundamental dependencies.

    - name: Setup homebrew.
      ansible.builtin.import_tasks: tasks/homebrew.yml

    - name: Setup flatpak.
      ansible.builtin.import_tasks: tasks/flatpak.yml

    - name: Setup node.js.
      ansible.builtin.import_tasks: tasks/nodejs.yml

    - name: Setup rust.
      ansible.builtin.import_tasks: tasks/rust.yml

    # Configure/install software.

    - name: Setup alacritty.
      ansible.builtin.import_tasks: tasks/alacritty.yml

    - name: Setup anaconda.
      ansible.builtin.import_tasks: tasks/anaconda.yml

    - name: Setup bat.
      ansible.builtin.import_tasks: tasks/bat.yml

    - name: Setup dircolors.
      ansible.builtin.import_tasks: tasks/dircolors.yml

    - name: Setup direnv.
      ansible.builtin.import_tasks: tasks/direnv.yml

    - name: Setup emacs.
      ansible.builtin.import_tasks: tasks/emacs.yml

    - name: Setup exa.
      ansible.builtin.import_tasks: tasks/exa.yml

    - name: Setup fzf.
      ansible.builtin.import_tasks: tasks/fzf.yml

    - name: Setup git.
      ansible.builtin.import_tasks: tasks/git.yml

    - name: Setup i3/sway.
      ansible.builtin.import_tasks: tasks/i3.yml

    - name: Setup junction.
      ansible.builtin.import_tasks: tasks/junction.yml
      when: flatpak_installed

    - name: Setup rg.
      ansible.builtin.import_tasks: tasks/rg.yml

    - name: Setup starship.
      ansible.builtin.import_tasks: tasks/starship.yml

    - name: Setup tmux.
      ansible.builtin.import_tasks: tasks/tmux.yml

    - name: Setup xdg.
      ansible.builtin.import_tasks: tasks/xdg.yml

    - name: Setup xresources.
      ansible.builtin.import_tasks: tasks/xresources.yml

    - name: Setup zoxide.
      ansible.builtin.import_tasks: tasks/zoxide.yml

    # Setup shells.

    - name: Setup bash.
      ansible.builtin.import_tasks: tasks/bash.yml

    - name: Setup fish.
      ansible.builtin.import_tasks: tasks/fish.yml

    - name: Setup zsh.
      ansible.builtin.import_tasks: tasks/zsh.yml
