- hosts: targets
  tasks:
    - name: fetch dotfiles
      git:
        accept_hostkey: yes
        repo: git@github.com:f-koehler/dotfiles.git
        dest: ~/.dotfiles
    - name: symlinks in ~/.config/
      file:
        src: "~/.dotfiles/.config/{{ item }}"
        dest: "~/.config/{{ item }}"
        state: link
        force: yes
        follow: no
      loop:
        - alacritty
        - htop
        - i3
        - khal
        - kitty
        - nvim
        - offlineimap
        - polybar
        - ranger
        - rofi
        - vdirsyncer
    - name: symlinks in ~/
      file:
        src: "~/.dotfiles/{{ item }}"
        dest: "~/{{ item }}"
        state: link
        force: yes
        follow: no
      loop:
        - .dir_colors
        - .emacs.d
        - .fzf
        - .gitconfig
        - .mozilla
        - .scripts
        - .zsh.d

    - name: symlink zsh config
      file:
        src: ~/.zsh.d/init.zsh
        dest: ~/.zshrc
        state: link
        force: yes
        follow: no
    - name: symlink p10k config
      file:
        src: ~/.zsh.d/p10k.zsh
        dest: ~/.p10k.zsh
        state: link
        force: yes
        follow: no
    - name: configure xresources
      file:
        src: ~/.dotfiles/xresources/src/nord
        dest: ~/.Xresources
        state: link
        force: yes
        follow: no
    - name: configure xdefaults
      file:
        src: ~/.dotfiles/xresources/src/nord
        dest: ~/.Xdefaults
        state: link
        force: yes
        follow: no
    - name: make sure to use ~/.tmux.conf instead of ~/.config/tmux/tmux.conf
      file:
        path: ~/.config/tmux
        state: absent
    - name: link tmux.conf
      file:
        src: ~/.dotfiles/tmux/tmux.conf
        dest: ~/.tmux.conf
        state: link
        force: yes
        follow: no
    - name: link tmux dir
      file:
        src: ~/.dotfiles/tmux/
        dest: ~/.tmux
        state: link
        force: yes
        follow: no
    - name: configure vscodium 
      file:
        src: "~/.dotfiles/vscode"
        dest: "~/.config/VSCodium"
        state: link
        force: yes
        follow: no
    - name: configure vscode (OSS)
      file:
        src: "~/.dotfiles/vscode"
        dest: "~/.config/Code - OSS"
        state: link
        force: yes
        follow: no
    - name: configure vscode
      file:
        src: "~/.dotfiles/vscode"
        dest: "~/.config/Code"
        state: link
        force: yes
        follow: no
