- name: Deploy dotfiles.
  hosts: tailscale
  pre_tasks:
    - name: Load config.
      ansible.builtin.include_vars: config.yml
    - name: Determine special directories.
      ansible.builtin.set_fact:
        home: "{{ ansible_env.HOME }}"
        xdg_config_home: "{{ ansible_env.HOME }}/.config"
        xdg_cache_home: "{{ ansible_env.HOME }}/.cache"
        xdg_data_home: "{{ ansible_env.HOME }}/.local/share"
        xdg_state_home: "{{ ansible_env.HOME }}/.local/statstate"
    - name: Export special directories
      ansible.builtin.set_fact:
        exports: "{{ exports | default({}) | combine({'XDG_CONFIG_HOME': xdg_config_home, 'XDG_CACHE_HOME': xdg_cache_home, 'XDG_DATA_HOME': xdg_data_home, 'XDG_STATE_HOME': xdg_state_home}) }}"
    - name: Get username.
      ansible.builtin.command: id -un
      changed_when: false
      register: username_check
    - name: Get effective group.
      ansible.builtin.command: id -gn
      changed_when: false
      register: group_check
    - name: Store username/group.
      ansible.builtin.set_fact:
        username: "{{ username_check.stdout }}"
        group: "{{ group_check.stdout }}"
    - name: Alias xdg-open to open.
      ansible.builtin.set_fact:
        aliases: "{{ aliases + [['open', 'xdg-open']] }}"
      when: ansible_system|lower == "linux"
    - name: Check if system is using systemd.
      ansible.builtin.stat:
        path: /run/systemd/system
      register: systemd_stat
    - name: Store whether system is running systemd.
      ansible.builtin.set_fact:
        systemd_running: "{{ systemd_stat.stat.exists and systemd.stat.isDir }}"
    - name: Fix multiplexers on certain systemd systems.
      ansible.builtin.set_fact:
        aliases: "{{ aliases + [[tool, 'systemd-run --scope --user ' + tool]] }}"
      with_items:
        - tmux
        - screen
        - zellij
      loop_control:
        loop_var: tool
      when: systemd_running
  roles:
    - alacritty
    - bat
    - brew
    - conda
    - direnv
    - exa
    - fzf
    - git
    # - gnome
    - kde
    - keepassxc
    - rustup
    - ssh
    - starship
    - tldr
    - tmux
    - vim
    - xdg
    # - zoxide

    - nix
    - fish
    - zsh
