- name: Deploy dotfiles.
  hosts: all
  pre_tasks:
    - name: Load config.
      ansible.builtin.include_vars: config.yml
    - name: Determine special directories.
      ansible.builtin.set_fact:
        home: "{{ ansible_env.HOME }}"
        xdg_config_home: "{{ ansible_env.HOME }}/.config"
        xdg_cache_home: "{{ ansible_env.HOME }}/.cache"
        xdg_data_home: "{{ ansible_env.HOME }}/.local/share"
        xdg_state_home: "{{ ansible_env.HOME }}/.local/statstate"
    - name: Export special directories
      ansible.builtin.set_fact:
        exports: "{{ exports | default({}) | combine({'XDG_CONFIG_HOME': xdg_config_home, 'XDG_CACHE_HOME': xdg_cache_home, 'XDG_DATA_HOME': xdg_data_home, 'XDG_STATE_HOME': xdg_state_home}) }}"
    - name: Get username.
      ansible.builtin.command: id -un
      changed_when: false
      register: username_check
    - name: Get effective group.
      ansible.builtin.command: id -gn
      changed_when: false
      register: group_check
    - name: Store username/group.
      ansible.builtin.set_fact:
        username: "{{ username_check.stdout }}"
        group: "{{ group_check.stdout }}"
  roles:
    - alacritty
    - bat
    - brew
    - conda
    - direnv
    - exa
    - fzf
    - git
    # - gnome
    - kde
    - keepassxc
    - rustup
    - ssh
    - starship
    - tmux
    - vim
    - xdg
    - zoxide

    - fish
    - zsh
