- hosts: all
  pre_tasks:
    - name: Load config.
      ansible.builtin.include_vars: config.yml
  # roles:
  #   # - gtk
  #   # - kde
  #   # # - nvim
  #   # - polybar
  #   # # - ranger
  #   # - rofi
  #   # - symlinks
  tasks:
    - name: Setup fundamental dependencies.
      ansible.builtin.include_role:
        name: "{{ role }}"
      loop_control:
        loop_var: role
      loop:
        - flatpak
        - nodejs
        - rust

    - name: Setup software.
      ansible.builtin.include_role:
        name: "{{ role }}"
      loop_control:
        loop_var: role
      loop:
        - alacritty
        - anaconda
        - bat
        - dircolors
        - direnv
        - emacs
        - exa
        - fzf
        - git
        - gnome
        - i3
        - rg
        - starship
        - tmux
        # - xdg
        - xresources
        - zoxide

    - name: Setup shells.
      ansible.builtin.include_role:
        name: "{{ role }}"
      loop_control:
        loop_var: role
      loop:
        - bash
        - fish
        - zsh
