- name: Deploy dotfiles.
  hosts: all
  pre_tasks:
    - name: Load config.
      ansible.builtin.include_vars: config.yml
  roles:
    - alacritty
    - bat
    - direnv
    - exa
    - fzf
    - git
    - neovim
    - starship
    - tmux
    - xdg
    - zoxide

    - fish
    - zsh
