- name: find reachable hosts
  hosts: targets
  gather_facts: no
  tasks:
    - command: /bin/true
      register: result
      ignore_errors: yes
    - group_by: key=reachable
      when: result is success

- hosts: reachable
  roles:
    - anaconda
    - i3
    - polybar
    - symlinks
    - tmux
  tasks:
    - name: enable systemd user units
      systemd:
        name: "{{ item }}"
        enabled: yes
        state: started
        scope: user
      loop:
        - update-dotfiles-submodules.timer
        - update-flatpaks.timer
