- name: find reachable hosts
  hosts: all
  gather_facts: no
  tasks:
    - name: "run a dummy command on hosts, ignoring failures"
      ansible.builtin.command: /bin/true # noqa no-changed-when
      register: result
      ignore_errors: yes
    - name: "register reachable hosts"
      ansible.builtin.group_by:
        key: reachable
      when: result is success

- hosts: reachable
  roles:
    - info

    - anaconda
    - dircolors
    - emacs
    - fish
    - fzf
    - homebrew
    - i3
    # - nvim
    - polybar
    # - ranger
    - rofi
    - symlinks
    - tmux
    - xresources
    - zsh
