- name: find reachable hosts
  hosts: all
  gather_facts: no
  roles:
    - info

    - anaconda
    - dircolors
    - emacs
    - fish
    - fzf
    - homebrew
    - i3
    # - nvim
    - polybar
    # - ranger
    - rofi
    - symlinks
    - tmux
    - xresources
    # - zsh
