- name: Deploy dotfiles.
  hosts: all
  pre_tasks:
    - name: Load config.
      ansible.builtin.include_vars: config.yml
    - name: Determine special directories.
      ansible.builtin.set_fact:
        home: "{{ ansible_env.HOME }}"
        xdg_config_home: "{{ ansible_env.HOME }}/.config"
        xdg_cache_home: "{{ ansible_env.HOME }}/.cache"
        xdg_data_home: "{{ ansible_env.HOME }}/.local/share"
        xdg_state_home: "{{ ansible_env.HOME }}/.local/statstate"

    - name: Export special directories
      ansible.builtin.set_fact:
        exports: "{{ exports | default({}) | combine({'XDG_CONFIG_HOME': xdg_config_home, 'XDG_CACHE_HOME': xdg_cache_home, 'XDG_DATA_HOME': xdg_data_home, 'XDG_STATE_HOME': xdg_state_home}) }}"
  roles:
    - alacritty
    - bat
    - direnv
    - exa
    - fzf
    - git
    # - gnome
    - neovim
    - rustup
    - starship
    - tmux
    - xdg
    - zoxide

    - fish
    - zsh
