- hosts: all
  pre_tasks:
    - name: Load config.
      ansible.builtin.include_vars: config.yml
  pre_tasks:
    - name: Find starship executable.
      ansible.builtin.set_fact:
        starship_path: "{{ path }}"
      with_first_found:
        - /usr/bin/starship
        - /usr/local/bin/starship
        - /opt/homebrew/bin/starship
      loop_control:
        loop_var: path
      changed_when: false

    - name: Find zoxide executable.
      ansible.builtin.set_fact:
        zoxide_path: "{{ path }}"
      with_first_found:
        - /usr/bin/zoxide
        - /opt/homebrew/bin/zoxide
      loop_control:
        loop_var: path
      changed_when: false

    - name: Find direnv executable.
      ansible.builtin.set_fact:
        direnv_path: "{{ path }}"
      with_first_found:
        - /usr/bin/direnv
        - /opt/homebrew/bin/direnv
      loop_control:
        loop_var: path
      changed_when: false
        
  roles:
    - zsh
    - neovim
    - alacritty