#!/bin/bash
set -euf -o pipefail

HOST="$(hostname)"
CONFIG="${HOST}.yml"

if [ ! -f ${CONFIG} ]; then
    echo "Missing config \"${CONFIG}\"!"
    echo "Use default.yml"
    CONFIG="default.yml"
fi

ansible-playbook -i targets ${CONFIG}
