# vim: ft=yaml.ansible
- hosts: targets
  roles:
    - alacritty
    - fzf
    - htop
    - keepassxc
    - kitty
    - neovim
    - pikaur
    - polybar
    - tmux
    - vscode
    - xresources
    - zsh
    - i3
    - nerd-fonts
    - rofi
    - vdirsyncer
    - ranger
