- name: configure xresources
  file:
    src: ~/.dotfiles/xresources/src/nord
    dest: ~/.Xresources
    state: link

- name: configure xdefaults
  file:
    src: ~/.dotfiles/xresources/src/nord
    dest: ~/.Xdefaults
    state: link
