- name: Create config dir.
  ansible.builtin.file:
    path: "{{ xdg_config_home }}/tealdeer"
    owner: "{{ username }}"
    group: "{{ group }}"
    mode: "0700"
    state: directory

- name: Generate config.
  ansible.builtin.template:
    src: config.toml
    dest: "{{ xdg_config_home }}/tealdeer/config.toml"
    owner: "{{ username }}"
    group: "{{ group }}"
    mode: "0700"
