#!/bin/bash
# set -euf -o pipefail

if [ "$1" == "mute" ]; then
    pamixer --toggle-mute
elif [ "$1" == "increase" ]; then
    pamixer -i 5
else
    pamixer -d 5
fi

VOLUME=$(pamixer --get-volume)
MUTED=$(pamixer --get-mute)

if [ "$MUTED" == "true" ]; then
    ICON=audio-volume-muted
else
    if [ "$VOLUME" -le 20 ]; then
        ICON=audio-volume-low
    elif [ "$VOLUME" -le 60 ]; then
        ICON=audio-volume-medium
    else
        ICON=audio-volume-high
    fi
fi

~/.local/bin/notify-send.py "Volume" "$VOLUME" \
    --hint string:image-path:$ICON boolean:transient:true \
    --replaces-process "change-volume" &
