#!/bin/bash
set -euf -o pipefail

notify-send \
    --urgency=normal \
    --expire-time=3000 \
    --icon=system-software-update \
    "Dotfiles" \
    "Update git submodules in ~/.dotfiles"

cd ~/.dotfiles
~/.scripts/git-update-submodules

if [ -z "$(git status --porcelain)" ]; then
    notify-send \
        --urgency=normal \
        --expire-time=3000 \
        --icon=dialog-information \
        "Dotfiles" \
        "~/.dotfiles is in a clean state"
else
    notify-send \
        --urgency=normal \
        --expire-time=3000 \
        --icon=dialog-warning \
        "Dotfiles" \
        "~/.dotfiles is in a dirty state, manual intervention required"
fi

~/.fzf/install --all
