- name: Check if bat is installed.
  ansible.builtin.stat:
    path: /usr/bin/bat
  register: bat_stat

- name: Install bat.
  community.general.homebrew:
    name: bat
    state: present
    path: ~/.linuxbrew/bin
  when: not (bat_stat.stat.exists and bat_stat.stat.executable)

- name: Remove homebrew bat.
  community.general.homebrew:
    name: bat
    state: absent
    path: ~/.linuxbrew/bin
  when: bat_stat.stat.exists and bat_stat.stat.executable
