- name: Check if direnv is installed.
  ansible.builtin.stat:
    path: /usr/bin/direnv
  register: direnv_stat

- name: Install direnv.
  community.general.homebrew:
    name: direnv
    state: present
    path: ~/.linuxbrew/bin
  when: not (direnv_stat.stat.exists and direnv_stat.stat.executable)

- name: Remove homebrew direnv.
  community.general.homebrew:
    name: direnv
    state: absent
    path: ~/.linuxbrew/bin
  when: direnv_stat.stat.exists and direnv_stat.stat.executable
