- name: Check if flatpak is installed.
  ansible.builtin.stat:
    path: /usr/bin/flatpak
  register: flatpak_stat

- name: Store whether flatpak is found.
  ansible.builtin.set_fact:
    flatpak_installed: "{{ flatpak_stat.stat.exists and flatpak_stat.stat.executable }}"

- name: Setup flatpak remotes.
  community.general.flatpak_remote:
    name: "{{ remote.name }}"
    flatpakrepo_url: "{{ remote.url }}"
    state: present
    method: user
  loop: "{{ flatpak_remotes }}"
  loop_control:
    loop_var: remote
  when: flatpak_installed
