- name: Clone repository.
  ansible.builtin.git:
    dest: "{{ homebrew_prefix }}/Homebrew"
    repo: https://github.com/Homebrew/brew
    version: "master"

- name: Create bin directory.
  ansible.builtin.file:
    path: "{{ homebrew_path }}"
    state: directory
    mode: 0700

- name: Symlink binary.
  ansible.builtin.file:
    src: "{{ homebrew_prefix }}/Homebrew/bin/brew"
    dest: "{{ homebrew_path }}/brew"
    state: link
