- name: Check if node is installed.
  ansible.builtin.stat:
    path: /usr/bin/node
  register: node_stat

- name: Install node.
  community.general.homebrew:
    name: node
    state: present
    path: "{{ homebrew_path }}"
  when: not (node_stat.stat.exists and node_stat.stat.executable)

- name: Remove homebrew node.
  community.general.homebrew:
    name: node
    state: absent
    path: "{{ homebrew_path }}"
  when: node_stat.stat.exists and node_stat.stat.executable

- name: Check if yarn is installed.
  ansible.builtin.stat:
    path: /usr/bin/yarn
  register: yarn_stat

- name: Install yarn.
  community.general.homebrew:
    name: yarn
    state: present
    path: "{{ homebrew_path }}"
  when: not (yarn_stat.stat.exists and yarn_stat.stat.executable)

- name: Remove homebrew yarn.
  community.general.homebrew:
    name: yarn
    state: absent
    path: "{{ homebrew_path }}"
  when: yarn_stat.stat.exists and yarn_stat.stat.executable
