- name: Check if starship is installed.
  ansible.builtin.stat:
    path: /usr/bin/starship
  register: starship_stat

- name: Store whether starship is missing.
  ansible.builtin.set_fact:
    starship_missing: "{{ not (starship_stat.stat.exists and starship_stat.stat.executable) }}"

- name: Use starship from homebrew.
  when: starship_missing and homebrew_enabled
  block:
    - name: Install starship.
      community.general.homebrew:
        name: starship
        state: present
        path: "{{ homebrew_path }}"
    - name: Store starship path.
      ansible.builtin.set_fact:
        starship_path: "{{ homebrew_path }}/starship"

- name: Use starship from system.
  when: (not starship_missing) and homebrew_present
  block:
    - name: Remove homebrew starship.
      community.general.homebrew:
        name: starship
        state: absent
        path: "{{ homebrew_path }}"
    - name: Store starship path.
      ansible.builtin.set_fact:
        starship_path: "/usr/bin/starship"

- name: Link starship config.
  ansible.builtin.file:
    src: "~/.dotfiles/files/starship.toml"
    dest: "~/.config/starship.toml"
    state: link
    force: yes
    follow: no
