- name: Check if starship is installed.
  ansible.builtin.stat:
    path: /usr/bin/starship
  register: starship_stat

- name: Install starship.
  community.general.homebrew:
    name: starship
    state: present
    path: ~/.linuxbrew/bin
  when: not (starship_stat.stat.exists and starship_stat.stat.executable)

- name: Remove homebrew starship.
  community.general.homebrew:
    name: starship
    state: absent
    path: ~/.linuxbrew/bin
  when: starship_stat.stat.exists and starship_stat.stat.executable

- name: Link starship config.
  ansible.builtin.file:
    src: "~/.dotfiles/files/starship.toml"
    dest: "~/.config/starship.toml"
    state: link
    force: yes
    follow: no
