- name: configure vscodium 
  file:
    src: "~/.dotfiles/vscode"
    dest: "~/.config/VSCodium"
    state: link
    force: yes
    follow: no

- name: configure vscode (OSS)
  file:
    src: "~/.dotfiles/vscode"
    dest: "~/.config/Code - OSS"
    state: link
    force: yes
    follow: no

- name: configure vscode
  file:
    src: "~/.dotfiles/vscode"
    dest: "~/.config/Code"
    state: link
    force: yes
    follow: no
