[cmd_duration]
format = 'took [⏱ $duration]($style)'

[directory]
read_only = " "

[docker_context]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[lua]
symbol = " "

[package]
symbol = " "

[python]
symbol = "  "

[rust]
symbol = " "
