- name: Store path.
  ansible.builtin.set_fact:
    direnv_path: "{{ direnv_check.path }}"

- name: Get zsh hook.
  ansible.builtin.command: "{{ direnv_path }} hook zsh"
  changed_when: false
  register: direnv_zsh_hook_result

- name: Register zsh hook.
  ansible.builtin.set_fact:
    zsh_hooks: "{{ zsh_hooks | combine({'direnv': direnv_zsh_hook_result.stdout}) }}"
  changed_when: false

- name: Get bash hook.
  ansible.builtin.command: "{{ direnv_path }} hook bash"
  changed_when: false
  register: direnv_bash_hook_result

- name: Register bash hook.
  ansible.builtin.set_fact:
    bash_hooks: "{{ bash_hooks | combine({'direnv': direnv_bash_hook_result.stdout}) }}"
  changed_when: false

- name: Get fish hook.
  ansible.builtin.command: "{{ direnv_path }} hook fish"
  changed_when: false
  register: direnv_fish_hook_result

- name: Register fish hook.
  ansible.builtin.set_fact:
    fish_hooks: "{{ fish_hooks | combine({'direnv': direnv_fish_hook_result.stdout}) }}"
  changed_when: false
