- name: Find executable.
  search_file:
    name: direnv
    paths:
      - /opt/homebrew/bin
      - /usr/bin
      - /run/current-system/sw/bin/
    executable: true
  register: direnv_check

- name: Store path.
  ansible.builtin.set_fact:
    direnv_path: "{{ direnv_check.path }}"
  when: direnv_check.found

- name: Get zsh hook.
  ansible.builtin.command: "{{ direnv_path }} hook zsh"
  changed_when: false
  when: direnv_path is defined
  register: direnv_zsh_hook_result

- name: Register zsh hook.
  ansible.builtin.set_fact:
    zsh_hooks: "{{ zsh_hooks + [direnv_zsh_hook_result.stdout + '\n'] }}"
  changed_when: false
  when: direnv_path is defined

- name: Get bash hook.
  ansible.builtin.command: "{{ direnv_path }} hook bash"
  changed_when: false
  when: direnv_path is defined
  register: direnv_bash_hook_result

- name: Register bash hook.
  ansible.builtin.set_fact:
    bash_hooks: "{{ bash_hooks + [direnv_bash_hook_result.stdout + '\n'] }}"
  changed_when: false
  when: direnv_path is defined

- name: Get fish hook.
  ansible.builtin.command: "{{ direnv_path }} hook fish"
  changed_when: false
  when: direnv_path is defined
  register: direnv_fish_hook_result

- name: Register fish hook.
  ansible.builtin.set_fact:
    fish_hooks: "{{ fish_hooks + [direnv_fish_hook_result.stdout + '\n'] }}"
  changed_when: false
  when: direnv_path is defined
