- name: Find executable.
  ansible.builtin.set_fact:
    direnv_path: "{{ path }}"
    zsh_hooks: "{{ zsh_hooks + ['source <(' + path + ' hook zsh)'] }}"
    bash_hooks: "{{ bash_hooks + ['source <(' + path + ' hook bash)'] }}"
    fish_hooks: "{{ fish_hooks + [path + ' hook fish | source'] }}"
  with_first_found:
    - files:
        - /usr/bin/direnv
        - /opt/homebrew/bin/direnv
      skip: true
  loop_control:
    loop_var: path
  changed_when: false
