- name: symlinks in ~/.config/
  file:
    src: "{{ role_path }}/files/config/{{ item }}"
    dest: "~/.config/{{ item }}"
    state: link
    force: yes
    follow: no
  loop:
    - alacritty
    - gtk-3.0
    - htop
    - khal
    - kitty
    - mpv
    - offlineimap
    - picom
    - rofi
    - systemd
    - vdirsyncer
  notify:
    - systemd reload
- name: symlinks in ~/
  file:
    src: "{{ role_path }}/files/home/{{ item }}"
    dest: "~/{{ item }}"
    state: link
    force: yes
    follow: no
  loop:
    - .condarc
    - .gitconfig
    - .scripts
    - .xinitrc
    - .ideavimrc
    - .profile
- name: flush handlers
  ansible.builtin.meta: flush_handlers
- name: enable systemd user units
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
    scope: user
  loop:
    - update-dotfiles-submodules.timer
    - update-flatpaks.timer
