- name: Create symlinks in ~/.config/.
  ansible.builtin.file:
    src: "~/.dotfiles/roles/symlinks/files/config/{{ item }}"
    dest: "~/.config/{{ item }}"
    state: link
    force: yes
    follow: no
  loop:
    - alacritty
    - htop
    - khal
    - kitty
    - mpv
    - offlineimap
    - picom
    - todoman
    - vdirsyncer
- name: Create symlinks in ~/.
  ansible.builtin.file:
    src: "~/.dotfiles/roles/symlinks/files/home/{{ item }}"
    dest: "~/{{ item }}"
    state: link
    force: yes
    follow: no
  loop:
    - .condarc
    - .gitconfig
    - .scripts
    - .xinitrc
    - .ideavimrc
    - .profile
