- name: Create symlinks in ~/.config/.
  ansible.builtin.file:
    src: "{{ role_path }}/files/config/{{ item }}"
    dest: "~/.config/{{ item }}"
    state: link
    force: yes
    follow: no
  loop:
    - alacritty
    - gtk-3.0
    - htop
    - khal
    - kitty
    - mpv
    - offlineimap
    - picom
    - todoman
    - vdirsyncer
- name: Create symlinks in ~/.
  ansible.builtin.file:
    src: "{{ role_path }}/files/home/{{ item }}"
    dest: "~/{{ item }}"
    state: link
    force: yes
    follow: no
  loop:
    - .condarc
    - .gitconfig
    - .scripts
    - .xinitrc
    - .ideavimrc
    - .profile
