- name: Create config dir.
  ansible.builtin.file:
    path: "{{ xdg_config_home }}/keepassxc"
    state: directory
    mode: "0700"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
      
- name: Enable browser integration.
  community.general.ini_file:
    path: "{{ xdg_config_home }}/keepassxc/keepassxc.ini"
    section: Browser
    option: "Enabled"
    value: "true"
    mode: "0600"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
      
- name: Enable ssh agent.
  community.general.ini_file:
    path: "{{ xdg_config_home }}/keepassxc/keepassxc.ini"
    section: SSHAgent
    option: Enabled
    value: "true"
    mode: "0600"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
      
- name: Enable minimize on close.
  community.general.ini_file:
    path: "{{ xdg_config_home }}/keepassxc/keepassxc.ini"
    section: GUI
    option: MinimizeOnClose
    value: "true"
    mode: "0600"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
      
- name: Enable minimize on startup.
  community.general.ini_file:
    path: "{{ xdg_config_home }}/keepassxc/keepassxc.ini"
    section: GUI
    option: MinimizeOnStartup
    value: "true"
    mode: "0600"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
      
- name: Enable minimize on to tray.
  community.general.ini_file:
    path: "{{ xdg_config_home }}/keepassxc/keepassxc.ini"
    section: GUI
    option: MinimizeToTray
    value: "true"
    mode: "0600"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
      
- name: Enable tray icon.
  community.general.ini_file:
    path: "{{ xdg_config_home }}/keepassxc/keepassxc.ini"
    section: GUI
    option: ShowTrayIcon
    value: "true"
    mode: "0600"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
      
- name: Set tray icon style.
  community.general.ini_file:
    path: "{{ xdg_config_home }}/keepassxc/keepassxc.ini"
    section: GUI
    option: TrayIconAppearance
    value: "monochrome-light"
    mode: "0600"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
      