- name: Find executable.
  search_file:
    name: exa
    paths:
      - /opt/homebrew/bin
      - /usr/bin
      - /run/current-system/sw/bin/
    executable: true
  register: exa_check

- name: Configure exa/ls.
  ansible.builtin.include_tasks: "{{ 'config.yml' if exa_check.found else 'config-fallback.yml' }}"
