- name: Check if exa is installed.
  ansible.builtin.stat:
    path: /usr/bin/exa
  register: exa_stat

- name: Store whether exa is installed.
  ansible.builtin.set_fact:
    exa_found: "{{ exa_stat.stat.exists and exa_stat.stat.executable }}"

- name: Store exa path.
  when: exa_found
  ansible.builtin.set_fact:
    exa_path: "/usr/bin/exa"
