- name: Check if installed.
  ansible.builtin.set_fact:
    exa_path: "{{ lookup('first_found', files, skip=True) }}"
  vars:
    files:
      - /usr/bin/exa
      - /opt/homebrew/bin/exa

- name: Add exa aliases.
  when: exa_path
  ansible.builtin.set_fact:
    aliases: "{{ aliases + [ alias, ] }}"
  loop:
    - ["ll", '{{ exa_path + " -lh --color=auto --icons"}}']
    - ["ls", '{{ exa_path + " --color=auto --icons"}}']
  loop_control:
    loop_var: alias

- name: Add ls aliases.
  when: not exa_path
  ansible.builtin.set_fact:
    aliases: "{{ aliases + [ alias, ] }}"
  loop:
    - ["ll", '{{ ls + " -lh --color=auto"}}']
    - ["ls", '{{ ls + " --color=auto"}}']
  loop_control:
    loop_var: alias
