- name: Create systemd user dir.
  ansible.builtin.file:
    path: "{{ directory }}"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0755
  loop_control:
    loop_var: directory
  loop:
    - "{{ xdg_config_home }}/systemd"
    - "{{ xdg_config_home }}/systemd/user"

- name: Create systemd user service file.
  ansible.builtin.template:
    src: ssh-agent.service
    dest: "{{ xdg_config_home }}/systemd/user/ssh-agent.service"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0644
  notify: Restart ssh-agent service.

- name: Flush handlers.
  meta: flush_handlers

- name: Enable ssh-agent service.
  ansible.builtin.systemd:
    name: ssh-agent.service
    state: started
    enabled: true
    scope: user

- name: Add shell hooks.
  ansible.builtin.set_fact:
    zsh_hooks: "{{ zsh_hooks + ['[[ -z \"${SSH_AUTH_SOCK}\" ]] && export SSH_AUTH_SOCK=\"' + home + '/.ssh/ssh-agent.socket\"\n'] }}"
