- name: Store path.
  ansible.builtin.set_fact:
    zoxide_path: "{{ zoxide_check.path }}"

- name: Get zsh hook.
  ansible.builtin.command: "{{ zoxide_path }} init zsh"
  changed_when: false
  register: zoxide_zsh_hook_result

- name: Register zsh hook.
  ansible.builtin.set_fact:
    zsh_hooks: "{{ zsh_hooks | combine({'zoxide': zoxide_zsh_hook_result.stdout}) }}"
  changed_when: false

- name: Get bash hook.
  ansible.builtin.command: "{{ zoxide_path }} init bash"
  changed_when: false
  register: zoxide_bash_hook_result

- name: Register bash hook.
  ansible.builtin.set_fact:
    bash_hooks: "{{ bash_hooks | combine({'zoxide': zoxide_bash_hook_result.stdout}) }}"
  changed_when: false

- name: Get fish hook.
  ansible.builtin.command: "{{ zoxide_path }} init fish"
  changed_when: false
  register: zoxide_fish_hook_result

- name: Register fish hook.
  ansible.builtin.set_fact:
    fish_hooks: "{{ fish_hooks | combine({'zoxide': zoxide_fish_hook_result.stdout}) }}"
  changed_when: false

- name: Add alias.
  ansible.builtin.set_fact:
    aliases: "{{ aliases + [['cd', 'z']] }}"
