- name: Find executable.
  search_file:
    name: zoxide
    paths:
      - /opt/homebrew/bin
      - /usr/bin
    executable: true
  register: zoxide_check
    
- name: Store path.
  ansible.builtin.set_fact:
    zoxide_path: "{{ zoxide_check.path }}"
  when: zoxide_check.found

- name: Get zsh hook.
  ansible.builtin.command: "{{ zoxide_path }} init zsh"
  changed_when: false
  when: zoxide_path is defined
  register: zoxide_zsh_hook_result

- name: Register zsh hook.
  ansible.builtin.set_fact:
    zsh_hooks: "{{ zsh_hooks + [zoxide_zsh_hook_result.stdout + '\n'] }}"
  changed_when: false
  when: (zoxide_path is defined) and (zoxide_zsh_hook_result is defined)

- name: Get bash hook.
  ansible.builtin.command: "{{ zoxide_path }} init bash"
  changed_when: false
  when: zoxide_path is defined
  register: zoxide_bash_hook_result

- name: Register bash hook.
  ansible.builtin.set_fact:
    bash_hooks: "{{ bash_hooks + [zoxide_bash_hook_result.stdout + '\n'] }}"
  changed_when: false
  when: (zoxide_path is defined) and (zoxide_bash_hook_result is defined)
