- name: Find executable.
  search_file:
    name: zoxide
    paths:
      - /opt/homebrew/bin
      - /usr/bin
      - /run/current-system/sw/bin/
    executable: true
  register: zoxide_check

- name: Configure zoxide.
  ansible.builtin.include_tasks: config.yml
  when: zoxide_check.found
