- name: Check if zoxide is installed.
  ansible.builtin.set_fact:
    zoxide_path: "{{ lookup('first_found', files, skip=True) }}"
  vars:
    files:
      - /usr/bin/zoxide
      - /opt/homebrew/bin/zoxide

- name: Configure.
  when: zoxide_path
  ansible.builtin.include_tasks:
    file: configure.yml
