- name: Find executable.
  ansible.builtin.set_fact:
    zoxide_path: "{{ path }}"
  with_first_found:
    - files:
        - /usr/bin/zoxide
        - /opt/homebrew/bin/zoxide
      skip: true
  loop_control:
    loop_var: path
  changed_when: false

- name: Get zsh hook.
  ansible.builtin.command: "{{ zoxide_path }} init zsh"
  changed_when: false
  when: zoxide_path is defined
  register: zoxide_zsh_hook_result

- name: Register zsh hook.
  ansible.builtin.set_fact:
    zsh_hooks: "{{ zsh_hooks + [zoxide_zsh_hook_result.stdout + '\n'] }}"
  changed_when: false
  when: zoxide_zsh_hook_result is defined

- name: Get bash hook.
  ansible.builtin.command: "{{ zoxide_path }} init bash"
  changed_when: false
  when: zoxide_path is defined
  register: zoxide_bash_hook_result

- name: Register bash hook.
  ansible.builtin.set_fact:
    bash_hooks: "{{ bash_hooks + [zoxide_bash_hook_result.stdout + '\n'] }}"
  changed_when: false
  when: zoxide_bash_hook_result is defined
