- name: Check if zsh is installed.
  ansible.builtin.stat:
    path: /usr/bin/nvim
  register: nvim_stat

- name: Install zsh.
  community.general.homebrew:
    name: zsh
    state: head
    path: ~/.linuxbrew/bin
  when: not (zsh_stat.stat.exists and zsh_stat.stat.executable)

- name: Remove homebrew zsh.
  community.general.homebrew:
    name: zsh
    state: absent
    path: ~/.linuxbrew/bin
  when: zsh_stat.stat.exists and zsh_stat.stat.executable

- name: Symlink zsh config.
  ansible.builtin.file:
    src: "~/.dotfiles/roles/zsh/files/{{ item }}"
    dest: "~/.{{ item }}"
    state: link
    force: yes
    follow: no
  loop:
    - zsh.d
    - zshrc
    - p10k.zsh

- name: Create plugin directory.
  ansible.builtin.file:
    path: ~/.zsh.d/plugins
    state: directory
    mode: "0700"

- name: Install zsh plugins.
  ansible.builtin.git:
    accept_hostkey: yes
    dest: "~/.zsh.d/plugins/{{ plugin['name'] }}"
    repo: "{{ plugin['repo'] }}"
    version: "{{ plugin['version'] }}"
  loop:
    - name: zsh-autosuggestions
      repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
      version: master
    - name: zsh-syntax-highlighting
      repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
      version: master
    - name: powerlevel10k
      repo: "https://github.com/romkatv/powerlevel10k"
      version: master
    - name: conda-zsh-completion
      repo: "https://github.com/esc/conda-zsh-completion"
      version: master
    - name: zsh-yarn-autocompletions
      repo: "https://github.com/g-plane/zsh-yarn-autocompletions"
      version: master
  loop_control:
    loop_var: plugin
