- name: Find executable.
  search_file:
    name: zsh
    paths:
      - /opt/homebrew/bin
      - /usr/bin
      - "/etc/profiles/per-user/{{ username }}/bin/"
      - /run/current-system/sw/bin/
    executable: true
  register: zsh_check

- name: Configure zsh.
  ansible.builtin.include_tasks: config.yml
  when: zsh_check.found
