- name: Create config directories.
  ansible.builtin.file:
    path: "{{ directory }}"
    state: directory
    mode: "0700"
  loop:
    - "{{ home }}/.zsh.d"
    - "{{ home }}/.zsh.d/plugins"
  loop_control:
    loop_var: directory


- name: Find executable.
  search_file:
    name: zsh
    paths:
      - /opt/homebrew/bin
      - /usr/bin
      - /run/current-system/sw/bin/
    executable: true
  register: zsh_check

- name: Install plugins.
  ansible.builtin.git:
    accept_hostkey: yes
    dest: "{{ home }}/.zsh.d/plugins/{{ plugin.name }}"
    repo: "{{ plugin.repo }}"
    update: true
  loop:
    - name: zsh-autopair
      repo: "https://github.com/hlissner/zsh-autopair"
      version: master
    - name: zsh-autosuggestions
      repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
      version: master
    - name: zsh-syntax-highlighting
      repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
      version: master
    - name: conda-zsh-completion
      repo: "https://github.com/conda-incubator/conda-zsh-completion"
      version: master
    - name: ohmyzsh
      repo: "https://github.com/ohmyzsh/ohmyzsh"
      version: master
  loop_control:
    loop_var: plugin

- name: Load zsh-autopair hook.
  ansible.builtin.slurp:
    src: "{{ home }}/.zsh.d/plugins/zsh-autopair/autopair.zsh"
  register: zsh_autopair_hook
    
- name: Register zsh-autopair hook.
  ansible.builtin.set_fact:
    zsh_hooks: "{{ zsh_hooks + [zsh_autopair_hook.content | b64decode + '\n' + 'autopair-init\n'] }}"

- name: Load zsh-autosuggestions hook.
  ansible.builtin.slurp:
    src: "{{ home }}/.zsh.d/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh"
  register: zsh_autosuggestions_hook
    
- name: Register zsh-autosuggestions hook.
  ansible.builtin.set_fact:
    zsh_hooks: "{{ zsh_hooks + [zsh_autosuggestions_hook.content | b64decode + '\n'] }}"
    
- name: Register zsh-syntax-highlighting hook.
  ansible.builtin.set_fact:
    zsh_hooks: "{{ zsh_hooks + ['source ' + home + '/.zsh.d/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh\n'] }}"

- name: Load sudo hook.
  ansible.builtin.slurp:
    src: "{{ home }}/.zsh.d/plugins/ohmyzsh/plugins/sudo/sudo.plugin.zsh"
  register: zsh_sudo_hook
    
- name: Register sudo hook.
  ansible.builtin.set_fact:
    zsh_hooks: "{{ zsh_hooks + [zsh_sudo_hook.content | b64decode + '\n'] }}"

- name: Load dirhistory hook.
  ansible.builtin.slurp:
    src: "{{ home }}/.zsh.d/plugins/ohmyzsh/plugins/dirhistory/dirhistory.plugin.zsh"
  register: zsh_dirhistory_hook
    
- name: Register dirhistory hook.
  ansible.builtin.set_fact:
    zsh_hooks: "{{ zsh_hooks + [zsh_dirhistory_hook.content | b64decode + '\n'] }}"

- name: Generate zshrc.
  ansible.builtin.template:
    src: "templates/zshrc"
    dest: "{{ home }}/.zshrc"
    mode: "0700"
    validate: "{{ zsh_check.found | ternary(zsh_check.path + ' -ef %s', 'true %s') }}"