- name: Create config directories.
  ansible.builtin.file:
    path: "{{ directory }}"
    state: directory
    mode: "0700"
  loop:
    - "{{ home }}/.zsh.d"
    - "{{ home }}/.zsh.d/plugins"
  loop_control:
    loop_var: directory

- name: Template config files.
  ansible.builtin.template:
    src: "templates/zshrc"
    dest: "{{ home }}/.zshrc"
    mode: "0700"
    # validate: zsh -ef %s

- name: Install plugins.
  ansible.builtin.git:
    accept_hostkey: yes
    dest: "{{ home }}/.zsh.d/plugins/{{ plugin.name }}"
    repo: "{{ plugin.repo }}"
    update: true
  loop:
    - name: zsh-autosuggestions
      repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
      version: master
    - name: zsh-syntax-highlighting
      repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
      version: master
    - name: conda-zsh-completion
      repo: "https://github.com/esc/conda-zsh-completion"
      version: master
  loop_control:
    loop_var: plugin
