- name: symlink zsh config
  ansible.builtin.file:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "~/.{{ item }}"
    state: link
    force: yes
    follow: no
  loop:
    - zsh.d
    - zshrc
    - p10k.zsh

- name: install zsh-autosuggestions
  ansible.builtin.git:
    accept_hostkey: yes
    dest: ~/.zsh.d/plugins/zsh-autosuggestions
    repo: "https://github.com/zsh-users/zsh-autosuggestions.git"

- name: install zsh-syntax-highlighting
  ansible.builtin.git:
    accept_hostkey: yes
    dest: ~/.zsh.d/plugins/zsh-syntax-highlighting
    repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"

- name: install powerlevel10k
  ansible.builtin.git:
    accept_hostkey: yes
    dest: ~/.zsh.d/plugins/powerlevel10k
    repo: "https://github.com/romkatv/powerlevel10k"

- name: install conda-zsh-completion
  ansible.builtin.git:
    accept_hostkey: yes
    dest: ~/.zsh.d/plugins/conda-zsh-completion
    repo: "https://github.com/esc/conda-zsh-completion"

- name: install zsh-yarn-autocompletions
  ansible.builtin.git:
    accept_hostkey: yes
    dest: ~/.zsh.d/plugins/zsh-yarn-autocompletions
    repo: "https://github.com/g-plane/zsh-yarn-autocompletions"
