- name: Set default PDF viewer.
  xdg_mime:
    type: application/pdf
    application: okularApplication_pdf.desktop

- name: Set default PNG viewer.
  xdg_mime:
    type: image/png
    application: re.sonny.Junction.desktop

- name: Set default JPG viewer.
  xdg_mime:
    type: image/jpg
    application: re.sonny.Junction.desktop
