- name: Store path.
  ansible.builtin.set_fact:
    brew_path: "{{ brew_check.path }}"

- name: Get hook.
  ansible.builtin.command: "{{ brew_path }} shellenv"
  changed_when: false
  register: brew_hook_result

- name: Register zsh hook.
  ansible.builtin.set_fact:
    bash_hooks: "{{ bash_hooks | combine({'brew': brew_hook_result.stdout}) }}"
    zsh_hooks: "{{ zsh_hooks | combine({'brew': brew_hook_result.stdout + '\nexport FPATH=\"/opt/homebrew/share/zsh/site-functions:${FPATH}\"'}) }}"
  changed_when: false
