- name: Find executable.
  search_file:
    name: brew
    paths:
      - /opt/homebrew/bin
    executable: true
  register: brew_check

- name: Configure brew.
  ansible.builtin.include_tasks: config.yml
  when: brew_check.found
