- name: Create i3 and sway config directories.
  ansible.builtin.file:
    path: "~/.config/{{ directory }}"
    state: directory
    mode: 0750
  loop:
    - i3
    - sway
  loop_control:
    loop_var: directory

- name: Configure i3.
  ansible.builtin.template:
    src: main.conf
    dest: ~/.config/i3/config
    # validate: "~/.dotfiles/roles/i3/files/validate {{ wm }} %s"
    trim_blocks: false
    lstrip_blocks: false
    mode: 0640
  vars:
    wm: "i3"

- name: Configure sway.
  ansible.builtin.template:
    src: main.conf
    dest: ~/.config/sway/config
    # validate: "~/.dotfiles/roles/i3/files/validate {{ wm }} %s"
    trim_blocks: false
    lstrip_blocks: false
    mode: 0640
  vars:
    wm: "sway"
