- name: install i3 and friends
  include_tasks: "{{ tasks }}"
  with_first_found:
    - "install-{{ ansible_distribution | lower }}.yml"
  loop_control:
    loop_var: tasks
  when: root_access

- name: create i3 config dir
  file:
    path: ~/.config/i3
    state: directory
    mode: 0750

- name: configure i3
  template:
    src: main.conf
    dest: ~/.config/i3/config
    validate: "i3 -C %s"
    mode: 0640
