- name: Find executable.
  search_file:
    name: rustup
    paths:
      - "{{ home }}/.cargo/bin"
      - /opt/homebrew/bin
      - /usr/bin
      - "/etc/profiles/per-user/{{ username }}/bin/"
      - /run/current-system/sw/bin/
    executable: true
  register: rustup_check

- name: Configure rustup.
  ansible.builtin.include_tasks: config.yml
  when: rustup_check.found
