- name: Find executable.
  ansible.builtin.set_fact:
    rustup_path: "{{ path }}"
    # zsh_hooks: "{{ zsh_hooks + ['source <(' + path + ' hook zsh)'] }}"
    # bash_hooks: "{{ bash_hooks + ['source <(' + path + ' hook bash)'] }}"
    # fish_hooks: "{{ fish_hooks + [path + ' hook fish | source'] }}"
  with_first_found:
    - files:
        - "{{ HOME }}/.cargo/bin/rustup"
        - /usr/bin/rustup
      skip: true
  loop_control:
    loop_var: path
  changed_when: false

- name: Create directories for completions.
  ansible.builtin.file:
    path: "{{ directory }}"
    state: directory
    mode: "0700"
  loop:
    - "{{ HOME }}/.zfunc"
    - "{{ xdg['config_home'] }}/fish"
    - "{{ xdg['config_home'] }}/fish/completions"
    - "{{ xdg['data_home'] }}/bash-completion"
    - "{{ xdg['data_home'] }}/bash-completion/completions"
  loop_control:
    loop_var: directory

- name: Create zsh completions.
  ansible.builtin.shell: "{{ rustup_path }} completions zsh {{ tool }} >> {{ HOME }}/.zfunc/_{{ tool }}"
  args:
    creates: "{{ HOME }}/.zfunc/_{{ tool }}"
  loop:
    - cargo
    - rustup
  loop_control:
    loop_var: tool

- name: Create bash completions.
  ansible.builtin.shell: "{{ rustup_path }} completions bash {{ tool }} >> {{ xdg['data_home'] }}/bash-completion/completions/{{ tool }}"
  args:
    creates: "{{ xdg['data_home'] }}/bash-completion/completions/{{ tool }}"
  loop:
    - cargo
    - rustup
  loop_control:
    loop_var: tool

- name: Create fish completions.
  ansible.builtin.shell: "{{ rustup_path }} completions fish {{ tool }} >> {{ xdg['config_home'] }}/fish/completions/{{ tool }}.fish"
  args:
    creates: "{{ xdg['config_home'] }}/fish/completions/{{ tool }}.fish"
  loop:
    - rustup
  loop_control:
    loop_var: tool
