- name: Find executable.
  ansible.builtin.command: which dconf
  register: dconf_check
  changed_when: false
  ignore_errors: true
  failed_when: false

- name: Store path.
  ansible.builtin.set_fact:
    dconf_path: "{{ dconf_check.stdout }}"
  when: dconf_check.rc == 0

- name: Find executable.
  ansible.builtin.command: which gnome-extensions
  register: gnome_extensions_check
  changed_when: false
  ignore_errors: true
  failed_when: false

- name: Store path.
  ansible.builtin.set_fact:
    gnome_extensions_path: "{{ gnome_extensions_check.stdout }}"
  when: gnome_extensions_check.rc == 0

- name: Load settings tasks.
  ansible.builtin.include_tasks:
    file: settings.yml
  when: dconf_path is defined

- name: Load extensions tasks.
  ansible.builtin.include_tasks:
    file: extensions.yml
  when: gnome_extensions_path is defined
