- name: Find dconf executable.
  ansible.builtin.set_fact:
    dconf_path: path
  with_first_found:
    - files:
        - /usr/bin/dconf
      skip: true
  changed_when: false

- name: Find gnome-extensions executable.
  ansible.builtin.set_fact:
    gnome_extensions_path: path
  with_first_found:
    - files:
        - /usr/bin/gnome-extensions
      skip: true
  changed_when: false

- name: Load settings tasks.
  ansible.builtin.include_tasks:
    file: settings.yml
  when: dconf_path is defined

- name: Load extensions tasks.
  ansible.builtin.include_tasks:
    file: extensions.yml
  when: gnome_extensions_path is defined
