#!/bin/sh

if [[ $# -lt 1 ]]; then
    echo "No files specified!"
    exit 1
fi

for file in "$@"; do
    if [[ ! -e $file ]]; then
        touch $file
        echo "#!/usr/bin/env python3" >> $file
        echo "#-*- coding:utf-8 -*-" >> $file
        chmod +x $file
    fi
done

exit 0
