#!/bin/bash
git submodule init
git submodule update --recursive
git submodule foreach --recursive 'git fetch origin; git checkout $(git rev-parse --abbrev-ref HEAD); git reset --hard origin/$(git rev-parse --abbrev-ref HEAD); git submodule update --recursive; git clean -dfx'
