---
- name: Converge
  hosts: all
  tasks:
    - name: Update pacman cache.
      community.general.pacman:
        update_cache: yes
      when: ansible_os_family == "Archlinux"
      changed_when: false
    - name: Update apt cache.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == 'Debian'
      changed_when: false
    - name: Install dependencies.
      ansible.builtin.package:
        name:
          - bash
          - curl
          - git
        state: present
      changed_when: false

- hosts: reachable
  pre_tasks:
    - name: Clone dotfiles.
      ansible.builtin.git:
        accept-_hostkey: yes
        dest: "~/.dotfiles"
        repo: "git@github.com:f-koehler/dotfiles.git"
        version: main

- ansible.builtin.import_playbook: "../../playbook.yml"
