---
- name: Converge
  hosts: all
  tasks:
    - name: Update pacman cache.
      community.general.pacman:
        update_cache: yes
      when: ansible_os_family == "Archlinux"
    - name: Update apt cache.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == 'Debian'
    - name: Install git.
      ansible.builtin.package:
        name: git
        state: present

- ansible.builtin.import_playbook: ../../playbook.yml
