---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: "${MOLECULE_IMAGE:-fabiankoehler/ubuntu1804-ansible:latest}"
    pre_build_image: true
provisioner:
  name: ansible
