- name: Find key-bindings (zsh).
  search_file:
    name: key-bindings.zsh
    paths:
      - "/opt/homebrew/Cellar/fzf/*/shell"
      - "/usr/share/fzf"
    glob: true
  register: fzf_key_bindings_zsh_check

- name: Find key-bindings (bash).
  search_file:
    name: key-bindings.bash
    paths:
      - "/opt/homebrew/Cellar/fzf/*/shell"
      - "/usr/share/fzf"
    glob: true
  register: fzf_key_bindings_bash_check


- name: Find completion (zsh).
  search_file:
    name: completion.zsh
    paths:
      - "/opt/homebrew/Cellar/fzf/*/shell"
      - "/usr/share/fzf"
    glob: true
  register: fzf_completion_zsh_check

- name: Find completion (bash).
  search_file:
    name: completion.bash
    paths:
      - "/opt/homebrew/Cellar/fzf/*/shell"
      - "/usr/share/fzf"
    glob: true
  register: fzf_completion_bash_check
  
- name: Add key-bindings (zsh).
  ansible.builtin.set_fact:
    zsh_hooks: "{{ zsh_hooks + [fzf_key_bindings_zsh_check.path] }}"
  when: fzf_key_bindings_zsh_check.found
  
- name: Add key-bindings (bash).
  ansible.builtin.set_fact:
    bash_hooks: "{{ bash_hooks + [fzf_key_bindings_bash_check.path] }}"
  when: fzf_key_bindings_bash_check.found
  
- name: Add completion (zsh).
  ansible.builtin.set_fact:
    zsh_hooks: "{{ zsh_hooks + [fzf_completion_zsh_check.path] }}"
  when: fzf_completion_zsh_check.found
  
- name: Add completion (bash).
  ansible.builtin.set_fact:
    bash_hooks: "{{ bash_hooks + [fzf_completion_bash_check.path] }}"
  when: fzf_completion_bash_check.found