- name: Find key-bindings (zsh).
  search_file:
    name: key-bindings.zsh
    paths:
      - "/opt/homebrew/Cellar/fzf/*/shell"
      - "/usr/share/fzf"
      - "/etc/profiles/per-user/{{ username }}/share/fzf"
      - "/run/current-system/sw/share/fzf/"
    glob: true
  register: fzf_key_bindings_zsh_check

- name: Find key-bindings (bash).
  search_file:
    name: key-bindings.bash
    paths:
      - "/opt/homebrew/Cellar/fzf/*/shell"
      - "/usr/share/fzf"
      - "/etc/profiles/per-user/{{ username }}/share/fzf"
      - "/run/current-system/sw/share/fzf/"
    glob: true
  register: fzf_key_bindings_bash_check

- name: Find completion (zsh).
  search_file:
    name: completion.zsh
    paths:
      - "/opt/homebrew/Cellar/fzf/*/shell"
      - "/usr/share/fzf"
      - "/etc/profiles/per-user/{{ username }}/share/fzf"
      - "/run/current-system/sw/share/fzf/"
    glob: true
  register: fzf_completion_zsh_check

- name: Find completion (bash).
  search_file:
    name: completion.bash
    paths:
      - "/opt/homebrew/Cellar/fzf/*/shell"
      - "/usr/share/fzf"
      - "/etc/profiles/per-user/{{ username }}/share/fzf"
      - "/run/current-system/sw/share/fzf/"
    glob: true
  register: fzf_completion_bash_check

- name: Add key-bindings (zsh).
  when: fzf_key_bindings_zsh_check.found
  block:
    - name: Read key-bindings (zsh).
      ansible.builtin.slurp:
        src: "{{ fzf_key_bindings_zsh_check.path }}"
      register: fzf_key_bindings_zsh_slurp
    - name: Add key-bindings (zsh).
      ansible.builtin.set_fact:
        zsh_hooks: "{{ zsh_hooks | combine({'fzf_key_bindings': fzf_key_bindings_zsh_slurp.content | b64decode}) }}"

- name: Add key-bindings (bash).
  when: fzf_key_bindings_bash_check.found
  block:
    - name: Read key-bindings (bash).
      ansible.builtin.slurp:
        src: "{{ fzf_key_bindings_bash_check.path }}"
      register: fzf_key_bindings_bash_slurp
    - name: Add key-bindings (bash).
      ansible.builtin.set_fact:
        bash_hooks: "{{ bash_hooks | combine({'fzf_key_bindings': fzf_key_bindings_bash_slurp.content | b64decode}) }}"

- name: Add completion (zsh).
  when: fzf_completion_zsh_check.found
  block:
    - name: Read completion (zsh).
      ansible.builtin.slurp:
        src: "{{ fzf_completion_zsh_check.path }}"
      register: fzf_completion_zsh_slurp
    - name: Add completion (zsh).
      ansible.builtin.set_fact:
        zsh_hooks: "{{ zsh_hooks | combine({'fzf_completion': fzf_completion_zsh_slurp.content | b64decode}) }}"

- name: Add completion (bash).
  when: fzf_completion_bash_check.found
  block:
    - name: Read completion (bash).
      ansible.builtin.slurp:
        src: "{{ fzf_completion_bash_check.path }}"
      register: fzf_completion_bash_slurp
    - name: Add completion (bash).
      ansible.builtin.set_fact:
        bash_hooks: "{{ bash_hooks | combine({'bash_completion': fzf_completion_bash_slurp.content | b64decode}) }}"
