- name: Fetch repo.
  ansible.builtin.git:
    accept_hostkey: yes
    update: yes
    depth: 1
    dest: ~/.fzf
    repo: https://github.com/junegunn/fzf.git
  notify:
    - Reinstall fzf.

- name: Install shell integration.
  ansible.builtin.command: "~/.fzf/install --update-rc --completion  --key-bindings --xdg"
  args:
    creates: "~/.config/fzf.{{ shell }}"
  loop:
    - bash
    - zsh
  loop_control:
    loop_var: shell

- name: Add zsh hook.
  ansible.builtin.set_fact:
    zsh_hooks: "{{ zsh_hooks + ['source ${HOME}/.config/fzf/fzf.zsh'] }}"

- name: Add bash hook.
  ansible.builtin.set_fact:
    bash_hooks: "{{ bash_hooks + ['source ${HOME}/.config/fzf/fzf.bash'] }}"
