- name: Create polybar config dir.
  ansible.builtin.file:
    path: ~/.config/polybar
    state: directory
    mode: 0750

- name: Configure polybar.
  ansible.builtin.template:
    src: main.conf
    dest: ~/.config/polybar/config
    trim_blocks: no
    mode: 0640
