- name: Clone rofi config.
  ansible.builtin.git:
    dest: ~/.config/rofi-configs
    repo: "https://github.com/f-koehler/rofi.git"
    version: master
  register: roficlone

- name: Setup configs.
  block:
    - name: Remove old backups.
      ansible.builtin.file:
        path: ~/.config/rofi.old
        state: absent
    - name: Run setup script.
      ansible.builtin.command:
        cmd: ~/.config/rofi-configs/setup.sh
        chdir: ~/.config/rofi-configs
        stdin: "1"
        stdin_add_newline: yes
  when: roficlone.changed
- name: Symlink scripts.
  ansible.builtin.file:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "~/.local/bin/{{ item }}"
    state: link
    force: yes
    follow: no
  loop:
    - app-launcher
    - power-menu
- name: Symlink power menu colors.
  ansible.builtin.file:
    src: "{{ role_path }}/files/power-menu.rasi"
    dest: "~/.config/rofi/powermenu/styles/colors.rasi"
    state: link
    force: yes
    follow: no
