- name: Check if tmux is installed.
  ansible.builtin.stat:
    path: /usr/bin/nvim
  register: nvim_stat

- name: Install tmux.
  community.general.homebrew:
    name: tmux
    state: head
    path: ~/.linuxbrew/bin
  when: not (tmux_stat.stat.exists and tmux_stat.stat.executable)

- name: Remove homebrew tmux.
  community.general.homebrew:
    name: tmux
    state: absent
    path: ~/.linuxbrew/bin
  when: tmux_stat.stat.exists and tmux_stat.stat.executable

- name: Remove config from old location.
  ansible.builtin.file:
    path: ~/.config/tmux
    state: absent

- name: Link tmux config.
  ansible.builtin.file:
    src: "~/.dotfiles/roles/tmux/files/tmux.conf"
    dest: ~/.tmux.conf
    state: link
    force: yes
    follow: no

- name: Install tmux plugins.
  ansible.builtin.git:
    accept_hostkey: yes
    dest: "~/.tmux/plugins/{{ plugin['name'] }}"
    repo: "{{ plugin['repo'] }}"
    version: "{{ plugin['version'] }}"
  loop:
    - name: tmux-sensible
      repo: "https://github.com/tmux-plugins/tmux-sensible"
      version: "master"
    - name: tmux-yank
      repo: "https://github.com/tmux-plugins/tmux-yank"
      version: master
    - name: tmux-resurrect
      repo: "https://github.com/tmux-plugins/tmux-resurrect"
      version: master
    - name: tmux-continuum
      repo: "https://github.com/tmux-plugins/tmux-continuum"
      version: master
    - name: tmux-tilish
      repo: "https://github.com/jabirali/tmux-tilish"
      version: master
    - name: nord-tmux
      repo: "https://github.com/arcticicestudio/nord-tmux"
      version: develop
  loop_control:
    loop_var: plugin
