- name: Remove config from old location.
  ansible.builtin.file:
    path: ~/.config/tmux
    state: absent

- name: Link tmux config.
  ansible.builtin.file:
    src: "{{ role_path }}/files/tmux.conf"
    dest: ~/.tmux.conf
    state: link
    force: yes
    follow: no

- name: "install tmux-sensible"
  ansible.builtin.git:
    accept_hostkey: yes
    dest: ~/.tmux/plugins/tmux-sensible
    repo: "https://github.com/tmux-plugins/tmux-sensible"
    version: master

- name: "install tmux-yank"
  ansible.builtin.git:
    accept_hostkey: yes
    dest: ~/.tmux/plugins/tmux-yank
    repo: "https://github.com/tmux-plugins/tmux-yank"
    version: master

- name: "install tmux-resurrect"
  ansible.builtin.git:
    accept_hostkey: yes
    dest: ~/.tmux/plugins/tmux-resurrect
    repo: "https://github.com/tmux-plugins/tmux-resurrect"
    version: master

- name: "install tmux-continuum"
  ansible.builtin.git:
    accept_hostkey: yes
    dest: ~/.tmux/plugins/tmux-continuum
    repo: "https://github.com/tmux-plugins/tmux-continuum"
    version: master

- name: "install tmux-tilish"
  ansible.builtin.git:
    accept_hostkey: yes
    dest: ~/.tmux/plugins/tmux-tilish
    repo: "https://github.com/jabirali/tmux-tilish"
    version: master

- name: "install nord-tmux"
  ansible.builtin.git:
    accept_hostkey: yes
    dest: ~/.tmux/plugins/nord-tmux
    repo: "https://github.com/arcticicestudio/nord-tmux"
    version: develop
