- name: Check if tmux is installed.
  ansible.builtin.include_tasks:
    file: configure.yml
  with_first_found:
    files:
      - /usr/bin/tmux
      - /opt/homebrew/bin/tmux
    skip: True

- name: Remove config from old location.
  ansible.builtin.file:
    path: ~/.config/tmux
    state: absent
