- name: Check if anaconda is installed.
  ansible.builtin.stat:
    path: "{{ anaconda_prefix }}/bin/conda"
  register: conda_check

- name: Install anaconda.
  block:
    - name: Create ~/.local directory.
      ansible.builtin.file:
        path: ~/.local
        state: directory
        mode: "0700"

    - name: Download miniforge installer.
      ansible.builtin.get_url:
        url: "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-MacOSX-arm64.sh"
        dest: ~/.local/miniforge.sh
        mode: "u+x"

    - name: Install minigorge.
      ansible.builtin.command:
        cmd: "~/.local/miniforge.sh -b -p {{ anaconda_prefix }} -f"

    - name: Remove miniconda installer.
      ansible.builtin.file:
        dest: ~/.local/miniconda.sh
        state: absent
  when: not conda_check.stat.exists

- name: Install mamba.
  ansible.builtin.command:
    cmd: "{{ anaconda_prefix }}/bin/conda install -c conda-forge -n base -q -y mamba"
    creates: "{{ anaconda_prefix }}/bin/mamba"
