- name: check if anaconda is installed
  stat:
    path: ~/.local/opt/anaconda3/bin/conda
  register: conda_check
- name: install anaconda
  block:
    - name: download miniconda installer
      get_url:
        url: "https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh"
        dest: ~/.local/miniconda.sh
        mode: "u+x"
    - name: install miniconda
      command:
        cmd: ~/.local/miniconda.sh -b -p ~/.local/opt/anaconda3 -f
    - name: remove miniconda installer
      file:
        dest: ~/.local/miniconda.sh
        state: absent
  when: not conda_check.stat.exists
- name: install mamba
  command:
    cmd: ~/.local/opt/anaconda3/bin/conda install -c conda-forge -n base -q -y mamba
    creates: ~/.local/opt/anaconda3/bin/mamba