- name: install Ubuntu Mono Bold Italic Nerd Font Complete
  get_url:
    url: "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/UbuntuMono/Bold-Italic/complete/Ubuntu%20Mono%20Bold%20Italic%20Nerd%20Font%20Complete.ttf"
    dest: "~/.local/share/fonts/Ubuntu Mono Bold Italic Nerd Font Complete.ttf"
  notify: regenerate fontconfig cache

- name: install Ubuntu Mono Bold Nerd Font Complete
  get_url:
    url: "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/UbuntuMono/Bold/complete/Ubuntu%20Mono%20Bold%20Nerd%20Font%20Complete.ttf"
    dest: "~/.local/share/fonts/Ubuntu Mono Bold Nerd Font Complete.ttf"
  notify: regenerate fontconfig cache

- name: install Ubuntu Mono Italic Nerd Font Complete
  get_url:
    url: "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/UbuntuMono/Regular-Italic/complete/Ubuntu%20Mono%20Italic%20Nerd%20Font%20Complete.ttf"
    dest: "~/.local/share/fonts/Ubuntu Mono Italic Nerd Font Complete.ttf"
  notify: regenerate fontconfig cache

- name: install Ubuntu Mono Nerd Font Complete
  get_url:
    url: "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/UbuntuMono/Regular/complete/Ubuntu%20Mono%20Nerd%20Font%20Complete.ttf"
    dest: "~/.local/share/fonts/Ubuntu Mono Nerd Font Complete.ttf"
  notify: regenerate fontconfig cache
