- name: create font directory
  file:
    path: ~/.local/share/fonts
    recurse: yes
    state: directory

- name: install Hack Nerd Font
  unarchive:
    remote_src: yes
    src: "https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/Hack.zip"
    dest: ~/.local/share/fonts
  notify: regenerate fontconfig cache
