(defun pretty-mode/add-latex-greek-small ()
  (setq prettify-symbols-alist
	(append prettify-symbols-alist
		'(("\\alpha"   . ?α)
		  ("\\beta"    . ?β)
		  ("\\gamma"   . ?γ)
		  ("\\delta"   . ?δ)
		  ("\\epsilon" . ?ε)
		  ("\\zeta"    . ?ζ)
		  ("\\eta"     . ?η)
		  ("\\theta"   . ?θ)
		  ("\\iota"    . ?ι)
		  ("\\kappa"   . ?κ)
		  ("\\lambda"  . ?λ)
		  ("\\mu"      . ?μ)
		  ("\\nu"      . ?ν)
		  ("\\xi"      . ?ξ)
		  ("\\omicron" . ?ο)
		  ("\\pi"      . ?π)
		  ("\\rho"     . ?ρ)
		  ("\\sigma"   . ?σ)
		  ("\\tau"     . ?τ)
		  ("\\upsilon" . ?υ)
		  ("\\varphi"  . ?φ)
		  ("\\phi"     . ?ϕ)
		  ("\\chi"     . ?χ)
		  ("\\psi"     . ?ψ)
		  ("\\omega"   . ?ω)))))

(defun pretty-mode/add-latex-greek-capital ()
  (setq prettify-symbols-alist
	(append prettify-symbols-alist
		'(("\\Alpha"   . ?Α)
		  ("\\Beta"    . ?Β)
		  ("\\Gamma"   . ?Γ)
		  ("\\Delta"   . ?Δ)
		  ("\\Epsilon" . ?Ε)
		  ("\\Zeta"    . ?Ζ)
		  ("\\Eta"     . ?Η)
		  ("\\Theta"   . ?Θ)
		  ("\\Iota"    . ?Ι)
		  ("\\Kappa"   . ?Κ)
		  ("\\Lambda"  . ?Λ)
		  ("\\Mu"      . ?Μ)
		  ("\\Nu"      . ?Ν)
		  ("\\Xi"      . ?Ξ)
		  ("\\Omicron" . ?Ο)
		  ("\\Pi"      . ?Π)
		  ("\\Rho"     . ?Ρ)
		  ("\\Sigma"   . ?Σ)
		  ("\\Tau"     . ?Τ)
		  ("\\Upsilon" . ?Υ)

		  ("\\Phi"     . ?Φ)
		  ("\\Chi"     . ?Χ)
		  ("\\Psi"     . ?Ψ)
		  ("\\Omega"   . ?Ω)))))

(defun pretty-mode/add-latex-binary-operator ()
  (setq prettify-symbols-alist
	(append prettify-symbols-alist
		'(("\\pm"              . ?±)
		  ("\\mp"              . ?∓)
		  ("\\times"           . ?×)
		  ("\\circ"            . ?⚬)
		  ("\\bullet"          . ?•)
		  ("\\cap"             . ?∩)
		  ("\\sqcap"           . ?⊓)
		  ("\\sqcup"           . ?⊔)
		  ("\\vee"             . ?∨)
		  ("\\wedge"           . ?∧)
		  ("\\setminus"        . ?∖)
		  ("\\diamond"         . ?◇)
		  ("\\bigtriangleup"   . ?△)
		  ("\\bigtriangledown" . ?▽)
		  ("\\triangleleft"    . ?◃)
		  ("\\triangleright"   . ?▹)
		  ("\\lhd"             . ?◁)
		  ("\\rhd"             . ?▷)
		  ("\\oplus"           . ?⊕)
		  ("\\otimes"          . ?⊗)
		  ("\\odot"            . ?⊙)
		  ("\\bigcirc"         . ?◯)
		  ("\\dagger"          . ?†)
		  ("\\ddagger"         . ?‡)
		  ("\\amalg"           . ?⨿)))))

(defun pretty-mode/add-latex-relations ()
  (setq prettify-symbols-alist
	(append prettify-symbols-alist
		'(("\\leq"        . ?≤)
		  ("\\prec"       . ?≺)
		  ("\\preceq"     . ?⪯)
		  ("\\ll"         . ?≪)
		  ("\\subset"     . ?⊂)
		  ("\\subseteq"   . ?⊆)
		  ("\\sqsubset"   . ?⊏)
		  ("\\sqsubset"   . ?⊑)
		  ("\\in"         . ?∈)
		  ("\\vdash"      . ?⊦)
		  ("\\geq"        . ?≥)
		  ("\\succ"       . ?≻)
		  ("\\succeq"     . ?⪰)
		  ("\\gg"         . ?≫)
		  ("\\supset"     . ?⊃)
		  ("\\supseteq"   . ?⊇)
		  ("\\supset"     . ?⊐)
		  ("\\sqsupseteq" . ?⊒)
		  ("\\ni"         . ?∋)
		  ("\\dashv"      . ?⊣)
		  ("\\equiv"      . ?≡)
		  ("\\sim"        . ?~)
		  ("\\simeq"      . ?≃)
		  ("\\asymp"      . ?≍)
		  ("\\approx"     . ?≈)
		  ("\\cong"       . ?≅)
		  ("\\neq"        . ?≠)
		  ("\\doteq"      . ?≐)
		  ("\\propto"     . ?∝)
		  ("\\models"     . ?⊨)
		  ("\\perp"       . ?⟘)
		  ("\\mid"        . ?∣)
		  ("\\parallel"   . ?∥)
		  ("\\nparallel"  . ?∦)
		  ("\\bowtie"     . ?⋈)
		  ("\\join"       . ?⨝)
		  ("\\smile"      . ?⌣)
		  ("\\frown"      . ?⌢)))))

(defun pretty-mode/add-latex-arrows ()
  (setq prettify-symbols-alist
	(append prettify-symbols-alist
		'(("\\leftarrow"         . ?←)
		  ("\\rightarrow"        . ?→)
		  ("\\uparrow"           . ?↑)
		  ("\\downarrow"         . ?↓)
		  ("\\Leftarrow"         . ?⇐)
		  ("\\Rightarrow"        . ?⇒)
		  ("\\Uparrow"           . ?⇑)
		  ("\\Downarrow"         . ?⇓)
		  ("\\leftrightarrow"    . ?↔)
		  ("\\updownarrow"       . ?↕)
		  ("\\Leftrightarrow"    . ?⇔)
		  ("\\Updownarrow"       . ?⇕)
		  ("\\mapsto"            . ?↦)
		  ("\\hookleftarrow"     . ?↩)
		  ("\\hookrightarrow"    . ?↪)
		  ("\\leftharpoonup"     . ?↼)
		  ("\\leftharpoondown"   . ?↽)
		  ("\\rightharpoonup"    . ?⇀)
		  ("\\rightharpoondown"  . ?⇁)
		  ("\\rightleftharpoons" . ?⇌)
		  ("\\leftrightharpoons" . ?⇋)
		  ("\\leadsto"           . ?⤳)
		  ("\\nearrow"           . ?↗)
		  ("\\searrow"           . ?↘)
		  ("\\swarrow"           . ?↙)
		  ("\\nwarrow"           . ?↖)))))

(defun pretty-mode/add-latex-misc ()
  (setq prettify-symbols-alist
	(append prettify-symbols-alist
		'(("\\ldots"    . ?…)
		  ("\\cdots"    . ?⋯)
		  ("\\vdots"    . ?⋮)
		  ("\\ddots"    . ?⋱)
		  ("\\alpeh"    . ?ℵ)
		  ("\\hbar"     . ?ℏ)
		  ("\\emptyset" . ?∅)
		  ("\\nabla"    . ?∇)
		  ("\\surd"     . ?√)
		  ("\\sqrt"     . ?√)
		  ("\\top"      . ?⊤)
		  ("\\bot"      . ?⊥)
		  ("\\forall"   . ?∀)
		  ("\\exists"   . ?∃)
		  ("\\neg"      . ?¬)
		  ("\\partial"  . ?∂)
		  ("\\infty"    . ?∞)
		  ("\\Box"      . ?☐)))))

(defun pretty-mode/latex ()
  "Prettify symbols in LaTex mode."
  (pretty-mode/add-latex-greek-small)
  (pretty-mode/add-latex-greek-capital)
  (pretty-mode/add-latex-binary-operator)
  (pretty-mode/add-latex-relations)
  (pretty-mode/add-latex-arrows)
  (pretty-mode/add-latex-misc)
  )

(add-hook 'tex-mode-hook 'pretty-mode/latex)
(add-hook 'latex-mode-hook 'pretty-mode/latex)
(add-hook 'org-mode-hook 'pretty-mode/latex)
