- name: Get zsh hook.
  ansible.builtin.slurp:
    src: "{{ nix_check.stat.path }}"
  register: nix_zsh_hook

- name: Add hook.
  ansible.builtin.set_fact:
    zsh_hooks: "{{ zsh_hooks | combine({'nix': [nix_zsh_hook.content | b64decode}) }}"

- name: Create config dir.
  ansible.builtin.file:
    path: "{{ xdg_config_home }}/nix"
    state: directory
    owner: "{{ username }}"
    group: "{{ group }}"
    mode: "0700"

- name: Create config file.
  ansible.builtin.template:
    src: nix.conf
    dest: "{{ xdg_config_home }}/nix/nix.conf"
    owner: "{{ username }}"
    group: "{{ group }}"
    mode: "0600"
