- name: Check if nix is installed.
  ansible.builtin.stat:
    path: /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
  register: nix_check

- name: Configure nix.
  ansible.builtin.include_tasks: configure.yml
  when: nix_check.stat.exists