polybar_bars:
  right:
    modules_center:
      - pulseaudio
      - wired-network-enp6s0
      - filesystem-/
      - cpu
      - memory
    modules_left:
      - i3
    modules_right:
      - date
    monitor: HDMI-0
    tray: True
  left:
    modules_center:
      - pulseaudio
      - filesystem-/
      - cpu
      - memory
    modules_left:
      - i3
    modules_right:
      - date
    monitor: DVI-D-0
polybar_wired_networks:
  - enp6s0
polybar_filesystems:
  - /
