screens:
  DVI-D-0:
    resolution:
      x: 1920
      y: 1080
  HDMI-0:
    resolution:
      x: 1920
      y: 1080
    position:
      x: 1920
      y: 0
    primary: yes
polybar_bars:
  right:
    modules_center:
      - pulseaudio
      - wired-network-enp6s0
      - filesystem-/
      - cpu
      - memory
    modules_left:
      - i3
    modules_right:
      - date
    monitor: HDMI-0
    tray: True
  left:
    modules_center:
      - pulseaudio
      - filesystem-/
      - cpu
      - memory
    modules_left:
      - i3
    modules_right:
      - date
    monitor: DVI-D-0
polybar_wired_networks:
  - enp6s0
polybar_filesystems:
  - /
