keyboard:
  layout: de
  variant: nodeadkeys
screens:
  - x11: DVI-D-0
    resolution:
      x: 1920
      y: 1080
    position:
      x: 1920
      y: 0
    i3_workspaces: [8, 9, 10]
  - x11: HDMI-0
    resolution:
      x: 1920
      y: 1080
    primary: yes
    i3_workspaces: [1, 2, 3]
polybar_bars:
  right:
    modules_center:
      - pulseaudio
      - wireless-network-wlp2s0
      - filesystem-/
      - cpu
      - memory
    modules_left:
      - i3
    modules_right:
      - date
    monitor: HDMI-0
    tray: True
  left:
    modules_center:
      - pulseaudio
      - filesystem-/
      - cpu
      - memory
    modules_left:
      - i3
    modules_right:
      - date
    monitor: DVI-D-0
polybar_wireless_networks:
  - wlp2s0
polybar_filesystems:
  - /
gtk_theme_name: "Nordic"
gtk_icon_theme_name: "Papirus-Dark"
gtk_application_prefer_dark_theme: True
