polybar_bars:
  center:
    modules_center:
      - pulseaudio
      - wired-network-enp0s31f6
      - filesystem-/
      - cpu
      - memory
    modules_left:
      - i3
    modules_right:
      - date
    monitor: HDMI1
    tray: True
  left:
    modules_center:
      - pulseaudio
      - filesystem-/
      - cpu
      - memory
    modules_left:
      - i3
    modules_right:
      - date
    monitor: DP1
  right:
    modules_center:
      - pulseaudio
      - filesystem-/
      - cpu
      - memory
    modules_left:
      - i3
    modules_right:
      - date
    monitor: DP2
polybar_wired_networks:
  - enp0s31f6
polybar_filesystems:
  - /
