screens:
  DP1:
    resolution:
      x: 1920
      y: 1200
    rotate: left
  DP2:
    resolution:
      x: 1920
      y: 1200
    position:
      x: 3120
      y: 0
    rotate: left
  HDMI1:
    resolution:
      x: 1920
      y: 1200
    position:
      x: 1200
      y: 440
    primary: yes
polybar_bars:
  center:
    modules_center:
      - pulseaudio
      - wired-network-enp0s31f6
      - filesystem-/
      - cpu
      - memory
    modules_left:
      - i3
    modules_right:
      - date
    monitor: HDMI1
    tray: True
  left:
    modules_center:
      - pulseaudio
      - filesystem-/
      - cpu
      - memory
    modules_left:
      - i3
    modules_right:
      - date
    monitor: DP1
  right:
    modules_center:
      - pulseaudio
      - filesystem-/
      - cpu
      - memory
    modules_left:
      - i3
    modules_right:
      - date
    monitor: DP2
polybar_wired_networks:
  - enp0s31f6
polybar_filesystems:
  - /
