keyboard:
  layout: de
  variant: nodeadkeys
screens:
  - x11: DP1
    wayland: DP-1
    resolution:
      x: 1920
      y: 1200
    rotate: left
    i3_workspaces:
      - 5
      - 6
      - 7
  - x11: DP2
    wayland: DP-2
    resolution:
      x: 1920
      y: 1200
    position:
      x: 3120
      y: 0
    rotate: left
    i3_workspaces:
      - 8
      - 9
      - 0
  - x11: HDMI1
    wayland: HDMI-A-1
    resolution:
      x: 1920
      y: 1200
    position:
      x: 1200
      y: 440
    primary: yes
    i3_workspaces:
      - 1
      - 2
      - 3
      - 4
polybar_bars:
  center:
    modules_center:
      - pulseaudio
      - wired-network-enp0s31f6
      - filesystem-/
      - cpu
      - memory
    modules_left:
      - i3
    modules_right:
      - date
    monitor: HDMI1
    tray: True
  left:
    modules_center:
      - pulseaudio
      - filesystem-/
      - cpu
      - memory
    modules_left:
      - i3
    modules_right:
      - date
    monitor: DP1
  right:
    modules_center:
      - pulseaudio
      - filesystem-/
      - cpu
      - memory
    modules_left:
      - i3
    modules_right:
      - date
    monitor: DP2
polybar_wired_networks:
  - enp0s31f6
polybar_filesystems:
  - /
