- name: Generate config.
  ansible.builtin.template:
    src: "starship.toml"
    dest: "{{ xdg_config_home }}/starship.toml"
    mode: "0644"

- name: Find executable.
  search_file:
    name: starship
    paths:
      - /opt/homebrew/bin
      - /usr/bin
      - /run/current-system/sw/bin/
    executable: true
  register: starship_check

- name: Configure starship.
  ansible.builtin.include_tasks: config.yml
  when: starship_check.found