- name: Generate config.
  ansible.builtin.template:
    src: "starship.toml"
    dest: "{{ xdg['config_home'] }}/starship.toml"
    mode: "0644"

- name: Find executable.
  ansible.builtin.set_fact:
    starship_path: "{{ path }}"
    zsh_hooks: "{{ zsh_hooks + ['source <(' + path + ' init zsh --print-full-init)'] }}"
    bash_hooks: "{{ bash_hooks + ['source <(' + path + ' init bash --print-full-init)'] }}"
    fish_hooks: "{{ fish_hooks + [path + ' init fish --print-full-init | source'] }}"
  with_first_found:
    - /usr/bin/starship
    - /usr/local/bin/starship
    - /opt/homebrew/bin/starship
  loop_control:
    loop_var: path
  changed_when: false
