- name: Check if starship is installed.
  ansible.builtin.set_fact:
    starship_path: "{{ lookup('first_found', files, skip=True) }}"
  vars:
    files:
      - /usr/bin/starship
      - /opt/homebrew/bin/starship

- name: Link starship config.
  when: starship_path
  ansible.builtin.file:
    src: "{{ role_path }}/files/starship.toml"
    dest: "~/.config/starship.toml"
    state: link
    force: yes
    follow: no
