- name: Generate config.
  ansible.builtin.template:
    src: "starship.toml"
    dest: "{{ xdg['config_home'] }}/starship.toml"
    mode: "0644"

- name: Find executable.
  ansible.builtin.set_fact:
    starship_path: "{{ path }}"
  with_first_found:
    - /usr/bin/starship
    - /usr/local/bin/starship
    - /opt/homebrew/bin/starship
  loop_control:
    loop_var: path
  changed_when: false

- name: Get zsh hook.
  ansible.builtin.command: "{{ starship_path }} init zsh --print-full-init"
  changed_when: false
  when: starship_path is defined
  register: starship_zsh_hook_result

- name: Register zsh hook.
  ansible.builtin.set_fact:
    zsh_hooks: "{{ zsh_hooks + [starship_zsh_hook_result.stdout + '\n'] }}"
  changed_when: false
  when: starship_zsh_hook_result is defined

- name: Get bash hook.
  ansible.builtin.command: "{{ starship_path }} init bash --print-full-init"
  changed_when: false
  when: starship_path is defined
  register: starship_bash_hook_result

- name: Register bash hook.
  ansible.builtin.set_fact:
    bash_hooks: "{{ bash_hooks + [starship_bash_hook_result.stdout + '\\n'] }}"
  changed_when: false
  when: starship_bash_hook_result is defined

- name: Get fish hook.
  ansible.builtin.command: "{{ starship_path }} init fish --print-full-init"
  changed_when: false
  when: starship_path is defined
  register: starship_fish_hook_result

- name: Register fish hook.
  ansible.builtin.set_fact:
    fish_hooks: "{{ fish_hooks + [starship_fish_hook_result.stdout + '\\n'] }}"
  changed_when: false
  when: starship_fish_hook_result is defined
