- name: Create config directories.
  ansible.builtin.file:
    path: "{{ directory }}"
    state: directory
    mode: "0700"
  loop:
    - "{{ xdg_config_home }}/nvim"
  loop_control:
    loop_var: directory

- name: Generate config.
  ansible.builtin.template:
    src: "templates/init.vim"
    dest: "{{ dest }}"
    mode: "0644"
  loop:
    - "{{ xdg_config_home }}/nvim/init.vim"
    - "{{ home }}/.vimrc"
  loop_control:
    loop_var: dest

- name: Install plugins.
  ansible.builtin.git:
    repo: "{{ instance.1.repo }}"
    dest: "{{ instance.0 }}/{{ instance.1.name }}"
    version: "{{ instance.1.version }}"
    update: true
    accept_hostkey: true
  loop: "{{ [xdg_data_home + '/nvim/site/pack/plugins/start', home + '/.vim/pack/plugins/start'] | product(vim_plugins) | list }}"
  loop_control:
    loop_var: instance
