- name: Find executable.
  search_file:
    name: conda
    paths:
      - "{{ home }}/.local/opt/anaconda3/bin/"
      - "{{ home }}/anaconda3/bin/"
      - "/opt/anconda3/bin/"
    executable: true
  register: conda_check

- name: Configure conda.
  ansible.builtin.include_tasks: config.yml
  when: conda_check.found