- name: Create config dir.
  ansible.builtin.file:
    path: ~/.config/alacritty
    state: directory
    force: yes

- name: Generate config.
  ansible.builtin.template:
    src: "alacritty.yml"
    dest: "~/.config/alacritty/alacritty.yml"
    mode: "0700"
