- name: Create config directories.
  ansible.builtin.file:
    path: "{{ directory }}"
    state: directory
    mode: "0700"
  loop:
    - "{{ xdg['config_home'] }}/alacritty"
  loop_control:
    loop_var: directory

- name: Generate config.
  ansible.builtin.template:
    src: "alacritty.yml"
    dest: "{{ xdg['config_home'] }}/alacritty/alacritty.yml"
    mode: "0700"
