flatpaks:
  - ch.protonmail.protonmail-bridge
  - com.bitwarden.desktop
  - com.discordapp.Discord
  - com.jgraph.drawio.desktop
  - com.skype.Client
  - im.riot.Riot
  - io.github.markummitchell.Engauge_Digitizer
  - org.signal.Signal
  - org.telegram.desktop
  - org.zotero.Zotero
  - us.zoom.Zoom