- name: install flatpaks (root)
  block:
    - name: install flatpak
      ansible.builtin.package:
        name: flatpak
      become: true
    - name: add flathub remote
      community.general.flatpak_remote:
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        method: system
        name: flathub
        state: present
    - name: install flatpaks
      community.general.flatpak:
        name: "{{ item }}"
        remote: flathub
        method: system
        state: present
      become: true
      loop: "{{ flatpaks }}"
    - name: remove user flatpaks
      community.general.flatpak:
        name: "{{ item }}"
        remote: flathub
        method: user
        state: absent
      loop: "{{ flatpaks }}"
  when: root_access
- name: install flatpaks (user)
  block:
    - name: add flathub remote
      community.general.flatpak_remote:
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        method: user
        name: flathub
        state: present
    - name: install flatpaks
      community.general.flatpak:
        name: "{{ item }}"
        remote: flathub
        method: user
        state: present
      become: true
      loop: "{{ flatpaks }}"
  when: not root_access
