- name: check if flatpak command exists
  stat:
    path: /usr/bin/flatpak
  register: flatpak_check

- name: flatpak tasks
  block:
    - name: add flathub flatpak repo
      flatpak_remote:
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        name: flathub
        state: present
        method: user
    - name: install flatpaks
      flatpak:
        name: "{{ item }}"
        state: present
        method: user
        remote: flathub
      loop:
        - com.spotify.Client
  when: flatpak_check.stat.exists