- name: install neovim
  include_tasks: "{{ tasks }}"
  with_first_found:
    - "install-{{ ansible_distribution | lower }}.yml"
    - "install-flatpak.yml"
  loop_control:
    loop_var: tasks

- name: clone LunarVim config
  ansible.builtin.git:
    dest: ~/.local/share/lunarvim/lvim
    repo: "https://github.com/ChristianChiarulli/LunarVim.git"
    version: "rolling"

- name: clone packer config
  ansible.builtin.git:
    dest: ~/.local/share/lunarvim/site/pack/packer/start/packer.nvim
    repo: https://github.com/wbthomason/packer.nvim
    version: "master"

- name: create nvim config dir
  ansible.builtin.file:
    path: ~/.config/lvim
    state: directory
    mode: 0700

- name: symlink config
  ansible.builtin.file:
    src: "{{ role_path }}/files/lv-config.lua"
    dest: "~/.config/lvim/lv-config.lua"
    state: link
    force: yes
    follow: no

- name: create ~/.local/bin
  ansible.builtin.file:
    path: ~/.local/bin
    state: directory
    mode: 0700

- name: symlink startup script
  ansible.builtin.file:
    src: "{{ role_path }}/files/lvim.sh"
    dest: "~/.local/bin/{{ item }}"
    state: link
    force: yes
    follow: no
  loop:
    - lvim
    - nvim
    - vim
