- name: Install LunarVim.
  ansible.builtin.shell: LVBRANCH=rolling yes no | bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/rolling/utils/installer/install.sh)
  args:
    creates: ~/.local/bin/lvim

- name: Symlink {vim, vi} -> {lvim}.
  ansible.builtin.file:
    src: "~/.local/bin/lvim"
    dest: "~/.local/bin/{{ item }}"
    state: link
    force: yes
    follow: no
  loop:
    - lvim
    - vim
