- name: Install LunarVim.
  ansible.builtin.command: "bash ~/.dotfiles/roles/nvim/files/deploy.sh"
  args:
    creates: ~/.local/bin/lvim

- name: Symlink {vim, vi} -> {lvim}.
  ansible.builtin.file:
    src: "~/.local/bin/lvim"
    dest: "~/.local/bin/{{ item }}"
    state: link
    force: yes
    follow: no
  loop:
    - vi
    - vim
