- name: Check if bat is installed.
  ansible.builtin.stat:
    path: /usr/bin/bat
  register: bat_stat

- name: Store whether bat is installed.
  ansible.builtin.set_fact:
    bat_found: "{{ bat_stat.stat.exists and bat_stat.stat.executable }}"

- name: Store bat path.
  when: bat_found
  ansible.builtin.set_fact:
    bat_path: "/usr/bin/bat"
