- name: Check if bat is installed.
  ansible.builtin.stat:
    path: /usr/bin/bat
  register: bat_stat

- name: Store whether bat is missing.
  ansible.builtin.set_fact:
    bat_missing: "{{ not (bat_stat.stat.exists and bat_stat.stat.executable) }}"

- name: Use bat from homebrew.
  when: bat_missing and homebrew_enabled
  block:
    - name: Install bat via homebrew.
      community.general.homebrew:
        name: bat
        state: present
        path: "{{ homebrew_path }}"
    - name: Store bat path.
      ansible.builtin.set_fact:
        bat_path: "{{ homebrew_path }}/bat"

- name: Use system bat.
  when: (not bat_missing) and homebrew_present
  block:
    - name: Remove homebrew bat.
      community.general.homebrew:
        name: bat
        state: absent
        path: "{{ homebrew_path }}"
    - name: Store bat path.
      ansible.builtin.set_fact:
        bat_path: "/usr/bin/bat"
