- name: Check if installed.
  ansible.builtin.set_fact:
    bat_path: "{{ lookup('first_found', files, skip=True) }}"
  vars:
    files:
      - /usr/bin/bat
      - /opt/homebrew/bin/bat

- name: Add alias.
  when: bat_path
  ansible.builtin.set_fact:
    aliases: '{{ aliases + [["cat", bat_path + " --color=always --italic-text=always --plain"]] }}'
