- name: Find executable.
  search_file:
    name: bat
    paths:
      - /opt/homebrew/bin
      - /usr/bin
      - "/etc/profiles/per-user/{{ username }}/bin"
      - /run/current-system/sw/bin/
    executable: true
  register: bat_check

- name: Store path and alias.
  ansible.builtin.set_fact:
    bat_path: "{{ bat_check.path }}"
    aliases: "{{ aliases + [['cat', bat_check.path + ' --plain --paging=never']] }}"
  when: bat_check.found
